### ISSUE TITLE
cmake build produces broken pkgconfig files

### ISSUE THREAD

**Issue by amluto** [sandstorm-io/capnproto#162]
I just installed from a git clone.  capnp.pc contains:

```
Version: 
```

capnp-rpc.pc contains:

```
Version: 
Libs: -L${libdir} -lcapnp-rpc -lkj-async
Requires: capnp = 
```

The result doesn't work (e.g. sandstorm won't build).  Manually shoving 0.5 into all three missing versions fixes it.

**Comment by kentonv** [comment]
Fixed by #177 (long ago)
