### ISSUE TITLE
Windows zip has linux line endings

### ISSUE THREAD

**Issue by mintyc** [sandstorm-io/capnproto#174]
Not a major problem as most compilers cope, but probably easy to fix!
Normally git checkouts on windows use CRLF.
Mix and matching edits between the two sources make GIT royally complain about line endings :)

**Comment by kentonv** [comment]
Thanks for the report. I'll see if I can do this in the release script for the next release.

(Though I kind of wish we could all just agree to use \n newlines, since most windows apps work just fine with it...)
