### ISSUE TITLE
Bump minimum gcc version to 4.8 in README/builds

### ISSUE THREAD

**Issue by llchan** [sandstorm-io/capnproto#175]
gcc-4.7 builds no longer work, and since the online docs have been updated to require gcc-4.8 or higher, I assume this is a deliberate change.  If so, we should update the README.md and build configs/scripts to catch this at configure time.

On the plus side, I learned about ref-qualifiers!  Don't think they're part of the C++11 Wikipedia page so missed them the first time around.

p.s. I think technically it requires gcc-4.8.1, but it's probably sufficient to say 4.8

**Comment by kentonv** [comment]
Wow, I apparently totally forgot that that readme exists. It still refers to the Cap'n Proto compiler coming in a separate package, which hasn't been the case since v0.1. :/
