### ISSUE TITLE
mingw stringify test failures

### ISSUE THREAD

**Issue by mintyc** [sandstorm-io/capnproto#180]
A couple of the stringify-test.c++ tests give different results for float fields with exponents - leading zero added to exponent on MinGW at least
e.g.
          "float32Field = -1.25e-010, "
but expected
          "float32Field = -1.25e-10, "

Perversely float64's don't have this problem

Modifying the test in a few places in the two tests that care allows a pass.

Since we have to work on various platforms I haven't got a sane fix as the output is compiler specific.
We could modify the tests to only use values that don't suffer this difference.

[Note by default mingw wont build the tests due to async and rpc libs not being available on any compiler on WIN32 (yet).
Modified my local build to update cmake logic and mod a few test files to run as much as possible.

Mingw skips a few heavy kj and capnp tests needing these libs but most extra tests run faultlessly.]

Over the weekend I'll try to update my fork with these changes and post a link here but they are not ideal (e.g. interface tests defined in test.capnp are just deleted in some cases, so I won't be submitting them in their current form)

**Comment by kentonv** [comment]
Oops, it looks like `RemoveE0()` in `kj/string.c++` needs to be fixed to work when the exponent is negative.

(I thing the best solution is to make the float stringification code produce the same output on all platforms. This should improve testability across the board.)

**Comment by mintyc** [comment]
FYI It also suffers with positive exponents too for float32

e.g. from stringify-test.c++
expected: "float32List = [0, 1234567, 1e37, -1e37, 1e-37, -1e-37], "
actual:     "float32List = [0, 1234567, 1e037, -1e037, 1e-037, -1e-037], "


a) Looks like char* FloatToBuffer(float value, char* buffer) is missing the
call to RemoveE0

b) RemoveE0 doesn't work with e-0

Since it will be in cache, this naive 2 pass might be OK

#if _WIN32
void RemoveE0(char* buffer) {
  // Remove redundant leading 0's after an e, e.g. 1e012 or e-012. Seems to
appear on
  // Windows.

  char *start = buffer;

  for (;;) {
    buffer = strstr(buffer, "e0");
    if (buffer == NULL || buffer[2] < '0' || buffer[2] > '9') {
      break;
    }
    memmove(buffer + 1, buffer + 2, strlen(buffer + 2) + 1);
  }
  // second pass to look for e-0
  buffer = start;
  for (;;) {
    buffer = strstr(buffer, "e-0");
    if (buffer == NULL || buffer[3] < '0' || buffer[3] > '9') {
      return;
    }
    memmove(buffer + 2, buffer + 3, strlen(buffer + 3) + 1);
  }
}
#endif

Sorry its not in the form of a pull request at the moment

**Comment by kentonv** [comment]
I think this was fixed in 940133d01d958e412a918dfbc90bdb8ad82d2278.
