### ISSUE TITLE
build with MinGW-W64

### ISSUE THREAD

**Issue by sbant** [sandstorm-io/capnproto#189]
after several hours... I finally built Cap’n Proto(not pycapnp) use the MinGW-W64 bundled within the WinPython.

I use CMake 3.2.0, and unchecked BUILD_TESTING
these files ok：
libcapnpc.a, libcapnp-rpc.a, libcapnp.a, libkj.a and capnp.exe, capnpc-c++.exe, capnpc-capnp.exe
this file failed
libkj-async.a (async-unix.c++ can not find < poll.h >)

maybe there need some change to replace the poll.h ?

**Comment by kentonv** [comment]
Hi sbant,

As mentioned on the installation page, currently we only support using MinGW-w64 to build Cap'n Proto in "lite" mode (CAPNP_LITE=1), or for building the `capnp` and associated tool binaries. At this time the RPC system is not supported at all for Win32. Porting it is possible but it will be a big project, as all the relevant system interfaces are all very different on Windows.

**Comment by kentonv** [comment]
As of #386 RPC works on MinGW.
