### ISSUE TITLE
GDB segfaults when debugging anything using kj-async or CAPNP_DEBUG_TYPES

### ISSUE THREAD

**Issue by RichardsonAlex** [sandstorm-io/capnproto#191]
The symbol kj::Quantity<decltype(((long)(1)) * ((long)(1))), kj::_::NanosecondLabel> kj::operator*<long, long, kj::_::NanosecondLabel>(long, kj::Quantity<long, kj::_::NanosecondLabel>) causes GDB (and c++filt) to crash while demangling it: https://sourceware.org/bugzilla/show_bug.cgi?id=18133. While this is an upstream bug in binutils, it makes it impossible to debug my application. It would be really nice if a workaround could be found.

**Comment by kentonv** [comment]
Yeah, I run into this all the time and it's really annoying. There is a work-around, though:

1. Start gdb without telling it an executable.
2. Disable demangling: `set demangle-style none`
3. Now load the executable: `file path/to/executable`
4. Proceed as normal... demangling names in your head. :(

**Comment by kentonv** [comment]
Also here is a previous bug report for the same problem:

https://sourceware.org/bugzilla/show_bug.cgi?id=17066

**Comment by a-richardson** [comment]
Thanks, didn't think about disabling demangling.

**Comment by kentonv** [comment]
(Thanks to @mortehu for introducing me to the work-around.)

**Comment by kentonv** [comment]
I believe this has long been fixed in gdb.
