### ISSUE TITLE
add a comand line option to the capnp schema compiler for specifying the output directory

### ISSUE THREAD

**Issue by eriksjolund** [sandstorm-io/capnproto#193]
I would like to be able to tell the capnp schema compiler with a command line option in which directory I want the generate the C++ files to be generated. Right now it seems that the compiler always generates the files in the same directory that the schema file is located.

Another thing: As for default behavior I would have expected the C++  files to be generated in the current working directory. In other words, I would have expected that "ls" would have shown the generated files in this example:

    user@linux:/tmp$ capnp --version
    Cap'n Proto version 0.5.1.2
    user@linux:/tmp$ mkdir /tmp/emptydir
    user@linux:/tmpb$ cd /tmp/emptydir
    user@linux:/tmp/emptydir$ capnp compile -oc++ /some/other/dir/format.capnp
    user@linux:/tmp/emptydir$ ls
    user@linux:/tmp/emptydir$

**Comment by eriksjolund** [comment]
I just realized that such an option already exist! When I read the output from "capnp help" at first I missed this line:

    user@linux:/tmp$ capnp help | grep "specific command"
    See 'capnp help <command>' for more information on a specific command.

The output dir can be set with this option:

    user@linux:/tmp$ capnp help compile | grep output
         -o<lang>[:<dir>], --output=<lang>[:<dir>]
             prefix for the purpose of deciding the names of output files.  For
    user@linux:/tmp$

Sorry, for the noise. Anyway, my second feature request still stands. Not so important, but I think it would be better if the generated files would by default be generated in the current working directory.

**Comment by dwrensha** [comment]
When we do this:

```
capnp compile -oc++:<OUT_DIR> --src-prefix=<PREFIX> <INPUT_FILE>
```

The compiler will remove `PREFIX` from the beginning of `INPUT_FILE` and then (if the result is not an absolute path) join the result to `OUT_DIR`.

In your case, you should see the output in the current directory if you do this:

```
capnp compile -oc++ --src-prefix=/tmp/other /tmp/other/format.capnp
```

**Comment by eriksjolund** [comment]
Thanks, it works!

    user@linux:/tmp$ mkdir emptydir
    user@linux:/tmp$ cd emptydir/
    user@linux:/tmp/emptydir$ ls
    user@linux:/tmp/emptydir$ capnp compile -oc++ --src-prefix=/tmp/other /tmp/other/format.capnp 
    user@linux:/tmp/emptydir$ ls
    format.capnp.c++  format.capnp.h

**Comment by kentonv** [comment]
Looks like this was resolved. Feel free to reopen if not.

**Comment by mikezackles** [comment]
In case it's helpful, I'd just like to point out that although this fix does work, this behavior is very unintuitive when the path to the capnp file is something like `../../foo.capnp`. The generated files end up in a random parent of the output directory, and `capnp help compile` doesn't mention this behavior under the --output flag. I'm sure there's probably a good reason for it to be this way, but to me this doesn't seem like the ideal default behavior.

**Comment by kentonv** [comment]
@mikezackles I agree that capnp should not allow output files to land outside of the specified output directory. We should canonicalize the output path and error out if it starts with "..". Can you file a bug for this?

**Comment by mikezackles** [comment]
Sure!
