### ISSUE TITLE
0.5.2 test failures on some esoteric debian archs

### ISSUE THREAD

**Issue by thomaslee** [sandstorm-io/capnproto#204]
0.5.2 has been packaged up & uploaded to Debian unstable. A few issues cropped up for some of the more esoteric archs: https://buildd.debian.org/status/package.php?p=capnproto&suite=unstable

**hurd-i386**

Fails to compile. Potential fix is open as a separate PR against the capnproto repo (see #202). We'll have to wait & see if the tests run with that.

**mips**

Seems to be AsyncUnixTest.SignalWith{Pointer,}Value value failing:
```
[ RUN      ] AsyncUnixTest.SignalWithValue
src/kj/async-unix-test.c++:89: Failure
Value of: info._sifields._rt.si_sigval.sival_int
  Actual: 0
Expected: 123
[  FAILED  ] AsyncUnixTest.SignalWithValue (0 ms)
[ RUN      ] AsyncUnixTest.SignalWithPointerValue
src/kj/async-unix-test.c++:112: Failure
Value of: info._sifields._rt.si_sigval.sival_ptr
  Actual: NULL
Expected: &port
Which is: 0x7fe67710 
[ FAILED ] AsyncUnixTest.SignalWithPointerValue (0 ms)
```

For a moment I thought it maybe related to [this](https://github.com/sandstorm-io/capnproto/blob/master/c++/src/kj/async-unix.c++#L455-L461), but then I would expect at least SignalWithPointerValue to work.

**mipsel and ppc64el**

Seems like the writeable promise is never invoked:

```
[ RUN      ] AsyncUnixTest.WriteObserver
src/kj/async-unix-test.c++:423: Failure
Value of: writable
  Actual: false
Expected: true
```

**powerpc**

powerpc exhibits *all* of the above issues.

**Comment by thomaslee** [comment]
To be clear: I'm still investigating this downstream and it's possible the bugs are on the Debian side, just wanted to raise it in case the reason for these failures are obvious to you.

**Comment by kentonv** [comment]
For the signals issue, I don't think we can blame the awkward union issue given that the `SignalWithPointerValue` case fails too, and in that case we're definitely reading from the correct field and not relying on any union shenanigans. Another possibility is that RT signals simply don't work on that platform, despite `SIGRTMIN` being defined. You should perhaps extend the `#if` from immediately before these tests to cover the broken platform as well.

For the WriteObserver issue, I'm not sure what to say. The test creates a pipe, write()s to it until it is full, then read()s 4k out of the read end and verifies that this causes the write end to become writable. It's possible that the kernel wants to wait for more space in the buffer as a low-watermark optimization, and this optimization is arch-dependent (perhaps based on page size). It than case you can fix the test by making it read() more data, perhaps in a loop until the pipe is empty.

**Comment by aborrero** [comment]
Hi,

just to let you know that I tried to build capnproto 0.5.2-2 debian in my mipsel machine with no issues.
How is this possible? Any hint?

**Comment by aborrero** [comment]
Hi,

after my local build was fine, capnproto was built again in debian buildd [0]. However it failed again:
 * it works in my mipsel board locally
 * it doesn't at debian buildd

I can't have access to the buildd ./test-suite.log file :-(

@kentonv, could you please provide a patch to address the issue?

thanks

[0] https://buildd.debian.org/status/fetch.php?pkg=capnproto&arch=mipsel&ver=0.5.2-2&stamp=1436959645

**Comment by latinovic** [comment]
Hi as I mentioned here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790571#15
AsyncUnixTest.WriteObserver fails on mips if the kernel PAGESIZE is larger that 4k.

If increase size of char buffer[4096]
(src/kj/async-unix-test.c++ +416)
to value of PAGESIZE or above, AsyncUnixTest.WriteObserver pass.

I was able to reproduce fallowing issue on EdgeRouter Pro:
> [  FAILED  ] AsyncUnixTest.SignalWithValue
> [  FAILED  ] AsyncUnixTest.SignalWithPointerValue
I will do further investigating..

**Comment by kentonv** [comment]
@aborrero I'm sorry, but I do not have time to debug obscure architectures. I am, however, happy to accept a patch if someone can come up with one.

FWIW, I strongly suspect that it's safe to ignore all of the problems I've seen reported. Cap'n Proto should work. In some cases (like the one @latinovic mentions), the test is bad. In the case of signals working weirdly, it may be a Cap'n Proto bug or it may be a kernel bug on that platform, however the problem should not affect Cap'n Proto in typical usage.

**Comment by aborrero** [comment]
Then dear @kentonv , would you help me to cleanly deactivate the offending test in mipsel?

**Comment by kentonv** [comment]
I think that should do it. If not, please provide a patch. I am coding blind here.

**Comment by aborrero** [comment]
On 31 July 2015 at 22:15, Kenton Varda <notifications@github.com> wrote:

> I think that should do it. If not, please provide a patch. I am coding
> blind here.
>
>
>
Ok thanks. I will give a test to the patch in following days.

-- 
Arturo Borrero González

**Comment by kentonv** [comment]
Note: I screwed up the original commit. You'll need both 35d7e17 and 33ebc2a. Sorry!

**Comment by thomaslee** [comment]
@kentonv I'm late to the party, somehow missed that you had already proposed a patch and wound up with my own, very similar-looking patch. A little more analysis/speculation over here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790571#32

Haven't verified myself on mipsel, but the issue is easily reproducible on x86_64 if you reduce the size of `buffer` (afaict it worked by chance on x86_64 because PIPE_BUF == 4096).

Suspect I'll need to get myself access to a porterbox to dig into the signal issue.

Thanks for the patch, sorry we didn't beat you to it. :)

**Comment by aborrero** [comment]
Unfortunately, while testing your patch:

```
[...]
make[6]: Entering directory '/tmp/buildd/capnproto-0.5.2/gtest'
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./build-aux  -I. -I./include -D_FORTIFY_SOURCE=2 -DGTEST_HAS_PTHREAD=1 -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -c -o src/gtest-all.lo src/gtest-all.cc
libtool: compile:  g++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./build-aux -I. -I./include -D_FORTIFY_SOURCE=2 -DGTEST_HAS_PTHREAD=1 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -c src/gtest-all.cc  -fPIC -DPIC -o src/.libs/gtest-all.o

In file included from src/gtest-all.cc:42:0:
./src/gtest.cc: In function 'testing::AssertionResult testing::internal::CmpHelperSTRCASENE(const char*, const char*, const char*, const char*)':
./src/gtest.cc:1222:1: internal compiler error: Segmentation fault
 }
 ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.


The bug is not reproducible, so it is likely a hardware or OS problem.
Makefile:1042: recipe for target 'src/gtest-all.lo' failed
[...]
```

**Comment by thomaslee** [comment]
@aborrero let's keep conversation on the Debian tracker -- seems unlikely an ICE is something for upstream to worry about. :+1:
