### ISSUE TITLE
GCC and Clang disagree on ABI in 0.6-dev

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/capnproto#212]
I have two c++ compilers on my system:

```
$ uname -a
Linux tantalum 3.19.1-x86_64-linode53 #1 SMP Tue Mar 10 15:30:28 EDT 2015 x86_64 GNU/Linux

$ g++ --version
g++ (GCC) 5.1.0

$ clang++ --version
clang version 3.6.1 (tags/RELEASE_361/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

Installing capnproto with the default autotools configuration uses g++. If I then try to compile simple programs with clang++, I get odd behavior:

```
// test.c++
#include <kj/debug.h>
int main() {
  KJ_LOG(ERROR, "hi");
  return 0;
}
```

```
$ clang++ -std=c++1y -I /usr/local/include -L /usr/local/lib -lkj -o test test.c++
$ ./test
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

If I instead compile with g++, I get the behavior I would expect:

```
$ g++ -std=c++1y -I /usr/local/include -L /usr/local/lib -lkj -o test test.c++
$ ./test
test.c++:4: error: hi
```

**Comment by kentonv** [comment]
Works fine on my machine.

    $ clang++ --version
    Debian clang version 3.5.2-1 (tags/RELEASE_352/final) (based on LLVM 3.5.2)
    Target: x86_64-pc-linux-gnu
    Thread model: posix

What distro?

**Comment by dwrensha** [comment]
> What distro?

Arch

**Comment by kentonv** [comment]
Wait, hmm, I rebuilt cap'n proto and re-installed and now I do actually see the problem!

**Comment by zarvox** [comment]
For tracking, https://llvm.org/bugs/show_bug.cgi?id=23764 is the LLVM bug that Kenton filed upstream.

**Comment by kentonv** [comment]
Maybe it's time to give up on the "disallow non-const copy" concept. It was meant to protect transitive constness of pointer-containing types, but it seems to lead to a lot of problems in practice. And if Clang insists on seeing such constructors as non-trivial, that could hurt performance... :/

**Comment by kentonv** [comment]
This problem was probably introduced by commit b059922 -- which has not been included in any release, thankfully.

**Comment by kentonv** [comment]
I guess if this is still an issue with modern GCC, it might be important to deal with before release, ugh...
