### ISSUE TITLE
Windows error in code outside LITE-protected code

### ISSUE THREAD

**Issue by scottpurdy** [sandstorm-io/capnproto#213]
https://ci.appveyor.com/project/numenta-ci/nupic-core/build/0.3.0.394#L234

We were successfully using the lite version with Windows but when I try to include `capnp/any.h` and use AnyPointers there appears to be a syntax error in common.h. Is this expected? Are AnyPointers omitted from the lite version?

**Comment by kentonv** [comment]
Hi Scott,

Is it possible that you have `#include`d `<windows.h>`, and it `#define`s `VOID` to `void`? Can you perhaps move your `windows.h` include so that it happens after the capnp includes, or `#undef VOID` between it and the capnp includes?

We should probably also detect this and complain.

**Comment by scottpurdy** [comment]
I did not consider that but will play around with it now and follow up.

**Comment by scottpurdy** [comment]
`#undef VOID` seemed to fix it. I vaguely remember this being an issue before but will try to keep it in mind in case it pops up again.
