### ISSUE TITLE
warnings during python build

### ISSUE THREAD

**Issue by glycerine** [sandstorm-io/capnproto#217]
With recent capnproto c++ sources, On Centos6.6 amd64, I get a bunch of compiler warnings when installing the python bindings. I'm not sure if these are really warning about anything real, but it would be preferred to quiet them if possible.

$ g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
...
$ python --version
Python 2.7.9

$  pip install pycapnp
Downloading/unpacking pycapnp
  Downloading pycapnp-0.5.6.tar.gz (428kB): 428kB downloaded
  Running setup.py egg_info for package pycapnp

Installing collected packages: pycapnp
  Running setup.py install for pycapnp
    cc -c /tmp/timer_createJcWUFH.c -o /tmp/tmplM9_w2/tmp/timer_createJcWUFH.o
    cc /tmp/tmplM9_w2/tmp/timer_createJcWUFH.o -o /tmp/tmplM9_w2/a.out
    /tmp/tmplM9_w2/tmp/timer_createJcWUFH.o: In function `main':
    timer_createJcWUFH.c:(.text+0x15): undefined reference to `timer_create'
    collect2: error: ld returned 1 exit status
    cc -c /tmp/tmplM9_w2/vers.cpp -o tmp/tmplM9_w2/vers.o --std=c++11
    cc tmp/tmplM9_w2/vers.o -lrt -o /tmp/tmplM9_w2/vers
    building 'capnp.lib.capnp' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I/usr/local/include/python2.7 -c capnp/lib/capnp.cpp -o build/temp.linux-x86_64-2.7/capnp/lib/capnp.o -\
-std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from capnp/lib/capnp.cpp:239:0:
    ./capnp/helpers/rpcHelper.h: In function ‘capnp::Capability::Client restoreHelper(capnp::RpcSystem<capnp::rpc::twoparty::VatId>&, capnp::MessageBuilder&)’:
    ./capnp/helpers/rpcHelper.h:42:72: warning: ‘capnp::Capability::Client capnp::RpcSystem<SturdyRefHostId>::restore(typename VatId::Reader, capnp::AnyPointer::Reader) [with VatId = capnp::rpc::twoparty::VatI\
d; typename VatId::Reader = capnp::rpc::twoparty::VatId::Reader]’ is deprecated (declared at /usr/local/include/capnp/rpc.h:441) [-Wdeprecated-declarations]
         return client.restore(hostId, objectId.getRoot<capnp::AnyPointer>());
                                                                            ^
    ./capnp/helpers/rpcHelper.h: In function ‘capnp::Capability::Client restoreHelper(capnp::RpcSystem<capnp::rpc::twoparty::VatId>&, capnp::MessageReader&)’:
    ./capnp/helpers/rpcHelper.h:49:72: warning: ‘capnp::Capability::Client capnp::RpcSystem<SturdyRefHostId>::restore(typename VatId::Reader, capnp::AnyPointer::Reader) [with VatId = capnp::rpc::twoparty::VatI\
d; typename VatId::Reader = capnp::rpc::twoparty::VatId::Reader]’ is deprecated (declared at /usr/local/include/capnp/rpc.h:441) [-Wdeprecated-declarations]
         return client.restore(hostId, objectId.getRoot<capnp::AnyPointer>());
                                                                            ^
    ./capnp/helpers/rpcHelper.h: In function ‘capnp::Capability::Client restoreHelper(capnp::RpcSystem<capnp::rpc::twoparty::VatId>&, capnp::AnyPointer::Reader&)’:
    ./capnp/helpers/rpcHelper.h:56:43: warning: ‘capnp::Capability::Client capnp::RpcSystem<SturdyRefHostId>::restore(typename VatId::Reader, capnp::AnyPointer::Reader) [with VatId = capnp::rpc::twoparty::VatI\
d; typename VatId::Reader = capnp::rpc::twoparty::VatId::Reader]’ is deprecated (declared at /usr/local/include/capnp/rpc.h:441) [-Wdeprecated-declarations]
         return client.restore(hostId, objectId);
                                               ^
    ./capnp/helpers/rpcHelper.h: In function ‘capnp::Capability::Client restoreHelper(capnp::RpcSystem<capnp::rpc::twoparty::VatId>&, capnp::AnyPointer::Builder&)’:
    ./capnp/helpers/rpcHelper.h:63:43: warning: ‘capnp::Capability::Client capnp::RpcSystem<SturdyRefHostId>::restore(typename VatId::Reader, capnp::AnyPointer::Reader) [with VatId = capnp::rpc::twoparty::VatI\
d; typename VatId::Reader = capnp::rpc::twoparty::VatId::Reader]’ is deprecated (declared at /usr/local/include/capnp/rpc.h:441) [-Wdeprecated-declarations]
         return client.restore(hostId, objectId);
                                               ^
    ./capnp/helpers/rpcHelper.h: In function ‘capnp::Capability::Client restoreHelper(capnp::RpcSystem<capnp::rpc::twoparty::VatId>&)’:
    ./capnp/helpers/rpcHelper.h:73:43: warning: ‘capnp::Capability::Client capnp::RpcSystem<SturdyRefHostId>::restore(typename VatId::Reader, capnp::AnyPointer::Reader) [with VatId = capnp::rpc::twoparty::VatI\
d; typename VatId::Reader = capnp::rpc::twoparty::VatId::Reader]’ is deprecated (declared at /usr/local/include/capnp/rpc.h:441) [-Wdeprecated-declarations]
         return client.restore(hostId, objectId);
                                               ^
    ./capnp/helpers/rpcHelper.h: In constructor ‘ServerContextRestorer::ServerContextRestorer(kj::Own<kj::AsyncIoStream>&&, capnp::SturdyRefRestorer<capnp::AnyPointer>&)’:
    ./capnp/helpers/rpcHelper.h:100:50: warning: ‘capnp::RpcSystem<VatId> capnp::makeRpcServer(capnp::VatNetwork<VatId, ProvisionId, RecipientId, ThirdPartyCapId, JoinResult>&, capnp::SturdyRefRestorer<LocalSt\
urdyRefObjectId>&) [with VatId = capnp::rpc::twoparty::VatId; LocalSturdyRefObjectId = capnp::AnyPointer; ProvisionId = capnp::rpc::twoparty::ProvisionId; RecipientId = capnp::rpc::twoparty::RecipientId; Third\
PartyCapId = capnp::rpc::twoparty::ThirdPartyCapId; JoinResult = capnp::rpc::twoparty::JoinResult]’ is deprecated (declared at /usr/local/include/capnp/rpc.h:483) [-Wdeprecated-declarations]
             rpcSystem(makeRpcServer(network, restorer)) {}
                                                      ^
    In file included from capnp/lib/capnp.cpp:240:0:
    ./capnp/helpers/asyncHelper.h: In member function ‘virtual bool PyEventPort::wait()’:
    ./capnp/helpers/asyncHelper.h:16:3: warning: no return statement in function returning non-void [-Wreturn-type]
       }
       ^
    ./capnp/helpers/asyncHelper.h: In member function ‘virtual bool PyEventPort::poll()’:
    ./capnp/helpers/asyncHelper.h:21:3: warning: no return statement in function returning non-void [-Wreturn-type]
       }
       ^
    capnp/lib/capnp.cpp: In function ‘int __pyx_pf_5capnp_3lib_5capnp_14TwoPartyServer___init__(__pyx_obj_5capnp_3lib_5capnp_TwoPartyServer*, PyObject*, PyObject*, PyObject*, PyObject*)’:
    capnp/lib/capnp.cpp:49351:189: warning: ‘capnp::RpcSystem<VatId> capnp::makeRpcServer(capnp::VatNetwork<VatId, ProvisionId, RecipientId, ThirdPartyCapId, JoinResult>&, capnp::SturdyRefRestorer<LocalSturdyR\
efObjectId>&) [with VatId = capnp::rpc::twoparty::VatId; LocalSturdyRefObjectId = capnp::AnyPointer; ProvisionId = capnp::rpc::twoparty::ProvisionId; RecipientId = capnp::rpc::twoparty::RecipientId; ThirdParty\
CapId = capnp::rpc::twoparty::ThirdPartyCapId; JoinResult = capnp::rpc::twoparty::JoinResult]’ is deprecated (declared at /usr/local/include/capnp/rpc.h:483) [-Wdeprecated-declarations]
           __pyx_v_self->thisptr = new  ::capnp::RpcSystem<capnp::rpc::twoparty::SturdyRefHostId>( ::capnp::makeRpcServer((*__pyx_v_self->_network->thisptr), (*__pyx_v_self->_restorer->thisptr)));
                                                                                                                                                                                                 ^
    capnp/lib/capnp.cpp: In function ‘PyObject* __pyx_f_5capnp_3lib_5capnp_7_Schema_get_dependency(__pyx_obj_5capnp_3lib_5capnp__Schema*, PyObject*, int)’:
    capnp/lib/capnp.cpp:52579:62: warning: ‘capnp::Schema capnp::Schema::getDependency(uint64_t) const’ is deprecated (declared at /usr/local/include/capnp/schema.h:765) [-Wdeprecated-declarations]
         __pyx_t_8 = __pyx_v_self->thisptr.getDependency(__pyx_t_7);
                                                                  ^
    capnp/lib/capnp.cpp: In function ‘PyObject* __pyx_f_5capnp_3lib_5capnp_13_StructSchema_get_dependency(__pyx_obj_5capnp_3lib_5capnp__StructSchema*, PyObject*, int)’:
    capnp/lib/capnp.cpp:54296:62: warning: ‘capnp::Schema capnp::Schema::getDependency(uint64_t) const’ is deprecated (declared at /usr/local/include/capnp/schema.h:765) [-Wdeprecated-declarations]
         __pyx_t_8 = __pyx_v_self->thisptr.getDependency(__pyx_t_7);
                                                                  ^
    capnp/lib/capnp.cpp: In function ‘PyObject* __pyx_f_5capnp_3lib_5capnp_16_InterfaceSchema_get_dependency(__pyx_obj_5capnp_3lib_5capnp__InterfaceSchema*, PyObject*, int)’:
    capnp/lib/capnp.cpp:56530:62: warning: ‘capnp::Schema capnp::Schema::getDependency(uint64_t) const’ is deprecated (declared at /usr/local/include/capnp/schema.h:765) [-Wdeprecated-declarations]
         __pyx_t_8 = __pyx_v_self->thisptr.getDependency(__pyx_t_7);
                                                                  ^
    g++ -pthread -shared build/temp.linux-x86_64-2.7/capnp/lib/capnp.o -lcapnpc -lcapnp-rpc -lcapnp -lkj-async -lkj -o build/lib.linux-x86_64-2.7/capnp/lib/capnp.so

    Installing capnpc-cython script to /fs1/raida/home/jason/penv/bin
Successfully installed pycapnp
Cleaning up...
$ g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
...
$ python --version
Python 2.7.9

**Comment by jparyani** [comment]
The main deprecation warnings are due to wrapping some old methods for
bootstrapping capabilities. I'm worried a lot of code has been written
using the old methods, and won't be removing this until it's removed
upstream.

The `get_dependency` deprecated functions will definitely be removed in the
v0.6.0 release as I've had a warning about it for a while now.

The PyEventPort warnings are easy to fix and just got lost in the noise.

**Comment by jparyani** [comment]
Also, this issue should probably be moved to [pycapnp's](https://github.com/jparyani/pycapnp) issue tracker, since it's all issues specific to it.

The only question for Kenton is how long the old RPC restore functions will stick around, since that's how long they'll remain in pycapnp.

**Comment by kentonv** [comment]
I haven't really decided. New apps should not use these methods simply because they were poorly-conceived and the new bootstrap capability mechanism is much better. However, there's no urgent need to remove the code; it isn't really getting in the way.

Are Python users receiving appropriate warnings when they use the Python versions of these functions?

**Comment by jparyani** [comment]
They weren't, but that was an oversight. Warnings have been added in https://github.com/jparyani/pycapnp/commit/bd0576b68a87813361a95b6a32d5b14f5583bb9e.

Kenton, feel free to close this issue whenever you feel like it. I've reopened it on pycapnp at https://github.com/jparyani/pycapnp/issues/71

**Comment by kentonv** [comment]
OK!
