### ISSUE TITLE
linker error: undefined reference to `capnp::ClientHook::NULL_CAPABILITY_BRAND'

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/capnproto#228]
`NULL_CAPABILITY_BRAND` is defined in capability.c++ but is used inline in capability.h. This is problematic because libcapnp is not supposed to have a link-time dependency on libcapnp-rpc.

The problem goes away if I move the definition of NULL_CAPABILITY_BRAND into layout.c++.

**Comment by Hoverbear** [comment]
We've noted this on our project as well. [Link](https://travis-ci.org/Hoverbear/raft/builds/72319662)

**Comment by kentonv** [comment]
Fixed by 96e9663.

@Hoverbear Any particular reason you're building directly from master rather than a release build? Master will be broken occasionally.

**Comment by Hoverbear** [comment]
@kentonv @dwrensha has also corrected me on this. We'll be moving to the latest release with my PR landing soon. Thanks!
