### ISSUE TITLE
benchmark/common.h: sem_init() is unsupported in OSX

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/capnproto#23]
In OSX, if I try to run the benchmarks with the "async" option, I get "premature EOF" errors.

The problem is that `sem_init()` is unsupported in OSX. It always fails and returns -1.

Therefore, I recommend at least checking the return value of `sem_init()` and printing an appropriate error message if it fails.

If you want to go farther, I did figure out a fix that seems to work in OSX:
https://github.com/dwrensha/capnproto/commit/8ec376775d4a41d8a8ba4ee58cecf04c48c529c9

I did not test the fix in Linux.

**Comment by kentonv** [comment]
Closing because I don't expect this will ever be fixed.
