### ISSUE TITLE
Converting Array<byte> <-> Array<word> is tedious and confusing

### ISSUE THREAD

**Issue by amit-e8** [sandstorm-io/capnproto#230]
Distribution: CentOS 7.1
Cap'n Proto: 0.5
Clang:  3.4.2 (tags/RELEASE_34/dot2-final)

When trying to execute the following code:
```
    const capnp::word *data = (const capnp::word*)blob.data();
    data_ = kj::heapArray(data, blob.size() / sizeof(capnp::word));
```

The result is the following errors:
```
/usr/include/kj/array.h:629:18: error: functional-style cast from 'capnp::word' to 'capnp::word' uses deleted function
    if (noexcept(T(*start))) {
                 ^~~~~~~~
/usr/include/kj/array.h:649:51: note: in instantiation of member function 'kj::_::CopyConstructArray_<capnp::word, capnp::word *, false>::apply' requested here
  return CopyConstructArray_<T, Decay<Iterator>>::apply(dst, start, end);
                                                  ^
/usr/include/kj/array.h:657:12: note: in instantiation of function template specialization 'kj::_::copyConstructArray<capnp::word, capnp::word *>' requested here
  pos = _::copyConstructArray(pos, start, end);
           ^
/usr/include/kj/array.h:670:11: note: in instantiation of function template specialization 'kj::ArrayBuilder<capnp::word>::addAll<capnp::word *>' requested here
  builder.addAll(content, content + size);
          ^
user/chorus/cluster/state_iterators.hh:32:17: note: in instantiation of function template specialization 'kj::heapArray<capnp::word>' requested here
    data_ = kj::heapArray(data, blob.size() / sizeof(capnp::word));
...
/usr/include/capnp/common.h:261:66: note: candidate constructor has been explicitly deleted
class word { uint64_t content KJ_UNUSED_MEMBER; KJ_DISALLOW_COPY(word); public: word() = default; };
                                                                 ^
/usr/include/kj/common.h:124:3: note: expanded from macro 'KJ_DISALLOW_COPY'
  classname(const classname&) = delete; \
```

Trying with data as non-const doesn't help.

**Comment by kentonv** [comment]
Hi Amit,

The code as you've written it, if it were allowed, would violate C++ strict aliasing rules (by copying 64-bit words and then reinterpreting them as other types when reading the message) and would also potentially result in unaligned access (slow on x86, SIGBUS on many architectures). The right thing to do here is use memcpy:

    data_ = kj::heapArray<capnp::word>(blob.size() / sizeof(capnp::word));
    memcpy(data_.asBytes().begin(), blob.begin(), data.asBytes().size());

Sorry for the confusion! We should probably add helper functions that work around these issues...

**Comment by amit-e8** [comment]
Thanks a lot @kentonv. I really appreciate the quick response and the detailed explanation. gcc wasn't complaining about this at all (using the exact same compilation flags)

**Comment by kentonv** [comment]
I think GCC has a longstanding bug where it considers types to be "trivial" even when they have deleted constructors, as is the case in with `capnp::word`. Meanwhile, the array construction code uses a GCC intrinsic to ask it if the type is trivial and, if so, automatically uses memcpy() rather than the type's constructor, thus avoiding the error about the constructor being deleted. Ironically I think this actually ends up meaning that alignment and aliasing problems are not problems on GCC. But it's totally by accident that that worked out.
