### ISSUE TITLE
C++ code generation for unions in generic structs with more than one type parameter is broken

### ISSUE THREAD

**Issue by jplatte** [sandstorm-io/capnproto#233]
I wrote a StackOverflow question about this and then immediately found the problem and answered the question myself. [Here][so]'s a link to it, because I don't like to repeat myself.

For some reason this worked for some time and then broke. I'm really confused as to why it worked before now that I've seen why the problem appears.

This should probably be a 5-minute-job to fix for someone who is familiar with the code, but I'd also look into the code myself and submit a PR if that's preferred.

[so]: http://stackoverflow.com/q/32011207/1592377

**Comment by kentonv** [comment]
Indeed! Thanks for clearly describing the problem. Even though I've run into this issue with macros before, I probably would have spent a few minutes confused.

Do you need a point release with this fix?

**Comment by jplatte** [comment]
No, not really. I only have this problem in one file that is hardly ever going to change, so for now I can work around it by manually changing the header whenever I do a clean rebuild.
