### ISSUE TITLE
Test `Exception/TrimSourceFilename` fails when building from outside source directory.

### ISSUE THREAD

**Issue by adrianratnapala** [sandstorm-io/capnproto#235]
With autotools, it is possible to build from outside the source directory by running `configure` from your desired build directory.   This works also with capnproto,  except that one of the unit tests fails when you run `make check`.

**To reproduce:**

* Get clean capnproto sources
* Make a build directory beside the sources.  Run `autoreconf` and ` configure` from there.
* Then run `make check`.

For example:

    mkdir test-cpnp
    cd test-cpnp
    git clone https://github.com/sandstorm-io/capnproto.git

    mkdir build
    cd build
    cpDir=../capnproto/c++

    autoreconf -i "$cpDir"
    "$cpDir/configure"
    make -j6 check

**Observation:**

`capnp-test` fails.  If we run it by hand we get

    [ TEST ] kj/exception-test.c++:30: legacy test: Exception/TrimSourceFilename  capnproto/c++/src/kj/exception-test.c++:31: failed: expected (trimSourceFilename("../capnproto/c++/src/kj/exception-test.c++")) == ("kj/exception-test.c++"); trimSourceFilename("../capnproto/c++/src/kj/exception-test.c++") = capnproto/c++/src/kj/exception-test.c++; kj/exception-test.c++
    stack: 0x42accd 0x42a6d5 0x7fe254f7ac6e 0x7fe254d5cd96 0x7fe254f7c241 0x7fe254f7d02d 0x7fe254d69048 0x7fe254d6a9c7 0x7fe254d5cd96 0x7fe254d6ab43 0x7fe254f7983f 0x7fe253f11790 0x41d979
    [ FAIL ] kj/exception-test.c++:30: legacy test: Exception/TrimSourceFilename

**NB:** If I build from inside the source directory, all tests pass.

**Expectation:**

All tests should pass, even when using a separate build directory.

**Comment by kentonv** [comment]
Hmm, I guess we've tested compiling from a `build` subdirectory but not from entirely out-of-tree.

Thanks for the report. FWIW, this only matters for making debug output a bit more readable. I'll try to fix it before the next release (for which there's no particular timeframe currently).

**Comment by adrianratnapala** [comment]
Yes suspected it was not very important.  The "fix" might simply be to weaken the test.  For example, you can make it XFAIL if it detects a "../" in certain place.

**Comment by frol** [comment]
FYI, I'm getting the same fail test using CMake and building in `<project_root>/build` folder (`cmake ../c++`).

**Comment by frol** [comment]
In fact, I have tried to build Cap'n Proto with CMake from different localtions:

* `<project_root>/`
* `<project_root>/build/`:
* `<project_root>/c++/`
* `<project_root>/c++/build/`

And the result was always EXACTLY the same:

```
/home/frol/miniconda3/conda-bld/work/capnproto-master/c++/src/kj/exception-test.c++:31: failed: expected (trimSourceFilename("/home/frol/miniconda3/conda-bld/work/capnproto-master/c++/src/kj/exception-test.c++")) == ("kj/exception-test.c++"); trimSourceFilename("/home/frol/miniconda3/conda-bld/work/capnproto-master/c++/src/kj/exception-test.c++") = /home/frol/miniconda3/conda-bld/work/capnproto-master/c++/src/kj/exception-test.c++; kj/exception-test.c++
1: stack: 0x425feb 0x424ad3 0x447a9e 0x450f96 0x44b5fa 0x44c23d 0x466051 0x467c67 0x450f96 0x467dd5 0x41393f 0x7f7d3db96710 0x4139d9
```

**Comment by frol** [comment]
I confirm that the test is fixed now. Thank you!

**Comment by adrianratnapala** [comment]
Works for me too.   (both from `master` and `22c1b62` itself).

And  kudos for respecting the mighty `goto`!
