### ISSUE TITLE
EzRpcClient: How to check for connecting failure?

### ISSUE THREAD

**Issue by jplatte** [sandstorm-io/capnproto#236]
The first lines of the doc comment for the EzRpcClient constructor only say that "appropriate exceptions" will be thrown later if connecting fails:

>  // Construct a new EzRpcClient and connect to the given address.  The connection is formed in
>  // the background -- if it fails, calls to capabilities returned by importCap() will fail with an
>  // appropriate exception.

I'm not using the deprecated importCap() function and its doc comment also doesn't say anything about the exceptions it might throw.

**Comment by kentonv** [comment]
Hi @jplatte,

Sorry for the delay. Sandstorm had a big launch last week and my email was backlogged well before that.

To answer your question, you should start by reading about KJ's exception philosophy here:

https://github.com/sandstorm-io/capnproto/blob/master/style-guide.md#exceptions

Basically, in most cases, you shouldn't worry yourself with what kinds of exceptions might be thrown, and you shouldn't even try to catch them. Assume that everything might throw arbitrary exceptions. If you catch them at all, usually you respond by canceling the operation and displaying the error text to the user; no need to determine what exactly went wrong programmatically.

One exception to this (so to speak) is that if you hold RPC connections open over long periods, you should catch exceptions where kj::Exception::getType() returns `DISCONNECTED`, and you should respond to them by re-establishing the underlying connection (including re-creating the EzRpcClient) and then retrying the operation. See kj/exception.h for more details.

**Comment by jplatte** [comment]
Sounds reasonable, thanks!
