### ISSUE TITLE
Suggested way of writing Capnp to file (#msg unknown)

### ISSUE THREAD

**Issue by RobinUS2** [sandstorm-io/capnproto#248]
What is the preferred way of writing capnp messages to a file with an infinite (unknown beforehand) length? Basically we use this as a backup on local disk apart from the typical kafka path.

We used to write TSV with newline to disk, but I can imagine a newline character is not ideal when using capnp. 

Is there some form of streaming list writer to a file descriptor? Or is there a character / magic byte we can use to separate messages (something that is never used by capnp messages).

Thanks for the help (might be good to add this to the documentation)!

**Comment by RobinUS2** [comment]
@kentonv Could you maybe help me out? Thanks!

**Comment by kentonv** [comment]
Hi Robin,

Good news! Cap'n Proto messages are naturally self-delimiting. You can simply call `writeMessageToFd()` repeatedly to write multiple messages to the same file, and then read them back by constructing StreamFdMessageReaders repeatedly (but make sure to only have one reader constructed at a time).

Does that answer your questioen?

**Comment by RobinUS2** [comment]
Yes, that's perfect, thanks!

**Comment by kentonv** [comment]
Cool, closing then.
