### ISSUE TITLE
Implement JSON decoding

### ISSUE THREAD

**Issue by kamalmarhubi** [sandstorm-io/capnproto#255]
@kentonv specified the API when he implemented the encoding side, which is here:

https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/compat/json.h

In particular, these methods need to be implemented:
- [`void JsonCodec::decodeRaw(kj::ArrayPtr<const char>, JsonValue::Builder)`](https://github.com/sandstorm-io/capnproto/blob/3871d11b4ce784c6a43d184cb3c535a3909b0183/c%2B%2B/src/capnp/compat/json.c%2B%2B#L214)
- [`void JsonCodec::decodeRaw(kj::ArrayPtr<const char>, DynamicStruct::Builder)`](https://github.com/sandstorm-io/capnproto/blob/3871d11b4ce784c6a43d184cb3c535a3909b0183/c%2B%2B/src/capnp/compat/json.c%2B%2B#L364)
- [`Orphan<DynamicValue> JsonCodec::decode(kj::ArrayPtr<const char>, Type, Orphanage)`](https://github.com/sandstorm-io/capnproto/blob/3871d11b4ce784c6a43d184cb3c535a3909b0183/c%2B%2B/src/capnp/compat/json.c%2B%2B#L368)

Mailing list post for context:
https://groups.google.com/d/topic/capnproto/viC9f44V9JY/discussion

**Comment by kamalmarhubi** [comment]
I'm trying this. So far I can parse things like: `null`, `true`, `false`, and arrays thereof. I created this issue to discuss design decisions and generally have somewhere to track it.

**Comment by kamalmarhubi** [comment]
@kentonv should non-ASCII `\u` character escapes be handled? The encoder just accepts that everything should be UTF-8, which makes sense because it can. For arbitrary input, the decoder could need to UTF-8 encode a code point provided as an escape.

**Comment by kamalmarhubi** [comment]
For now I'm going to make it throw if that happens, but ideally there would be a better story.

**Comment by kamalmarhubi** [comment]
Slightly more context: near as I can tell, there's nothing for this in `kj`. I don't particularly want to be responsible for a production-use UTF-8 encoder...

My current best idea is to adapt code from `jq`: https://github.com/stedolan/jq/blob/master/src/jv_parse.c#L430

It's MIT-licensed as well.

**Comment by kamalmarhubi** [comment]
Re unicode stuffs, found `<locale>` and `<cuchar>` which has some stuff that can help. Not sure of Cap'n Proto's stance on using stuff like `<locale>` though...

**Comment by kentonv** [comment]
Closing because JSON decoding has been working for a while now! There may be some missing bits (e.g. I think unicode escapes may not work) but we should raise those as individual issues and close this general issue.
