### ISSUE TITLE
JSON encoding allows inf, -inf, nan which are disallowed by spec

### ISSUE THREAD

**Issue by kamalmarhubi** [sandstorm-io/capnproto#261]
Compare to

```
» a = [0/0, 1/0, -1/0]
« [NaN, Infinity, -Infinity]
» JSON.stringify(a)
« "[null,null,null]"
```

as seen in console for both Chrome and Firefox.

**Comment by kamalmarhubi** [comment]
The spec also says

> Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not permitted.

**Comment by kamalmarhubi** [comment]
I don't think there's any way to roundtrip those values. I'll send a PR to fix the encoder; unsure what to do in the decoder. Probably replace with nan?

**Comment by kamalmarhubi** [comment]
```
» Number(JSON.parse(JSON.stringify(1/0)))
« 0
```

**Comment by kamalmarhubi** [comment]
Hrm, Python's `json` module allows all them:

```
>>> a = [float('nan'), float('inf'), float('-inf')]
>>> a
[nan, inf, -inf]
>>> json.dumps(a)
'[NaN, Infinity, -Infinity]'
>>> json.loads(json.dumps(a))
[nan, inf, -inf]
```

**Comment by kamalmarhubi** [comment]
Ruby has the same behaviour.

**Comment by kamalmarhubi** [comment]
And Go disallows them. I think it's unsafe the encode these values is the aim is interoperability with JSON-expecting systems. It may be acceptable to decode them, however #258 does not.

**Comment by kentonv** [comment]
How about encoding them as strings? We can make sure our own encoder and parser can round-trip these correctly (albeit treating all NaNs as equivalent, oh well).

Otherwise it seems like there's nothing reasonable we can do except throw an exception, but I think that would probably we worse for most apps.

**Comment by kamalmarhubi** [comment]
The existing encoding was already treating all NaNs as equivalent, so no loss there.

I don't know the main use case for the JSON codec, so it's hard for me to pick between alternatives. How about disallowing them by default, but adding a ready-made type handler for the string encoding?

**Comment by kentonv** [comment]
My worry is that this would be the *only* case where exceptions could be thrown at serialization time. Many users are likely to assume that serialization doesn't throw, so this could end up being a security issue: trick someone into JSON-ifying a message you send them that happens to contain infinity/nan, and now you've caused an exception where perhaps they weren't prepared for it. (Then again, people *should* be prepared for an exception to happen *anywhere*, but...)

I guess I would also be OK with a default of passing `null`, matching what `JSON.stringify()` does in Chrome.

**Comment by kamalmarhubi** [comment]
Ah, fair point with exceptions. PR coming for encoding as `null`.
