### ISSUE TITLE
capnp-maven-plugin

### ISSUE THREAD

**Issue by mtetreau** [sandstorm-io/capnproto#279]
Hi,

I wanted to let you know that our [Cap'n Proto maven plugin](https://github.com/expretio/capnp-maven-plugin) is now available as a SNAPSHOT on [nexus](https://oss.sonatype.org/#nexus-search;quick~org.expretio). It provides dynamic compilation of capnproto's definition schemas at build time. Generated java classes are automatically added to project source. The [capnp-native](https://github.com/expretio/capnp-maven-plugin) project bundles Cap'n Proto platform dependent compiler and java plugin into maven artifacts.

Thanks!

**Comment by kentonv** [comment]
Cool! Pinging @dwrensha, who maintains the Java port: https://github.com/dwrensha/capnproto-java

**Comment by dwrensha** [comment]
Thanks Marc! I've added a link to your plugin on the capnproto-java landing page: https://dwrensha.github.io/capnproto-java/index.html

**Comment by mtetreau** [comment]
Cool!
