### ISSUE TITLE
using "capnp compile -oc++ Map.capnp" command returned error:

### ISSUE THREAD

**Issue by greatestjie** [sandstorm-io/capnproto#280]
My "Map.capnp" file : 
@0xdc5b07d7180bb807;
struct Map(Key, Value) {
  entries @0 :List(Entry);
  struct Entry {
    key @0 :Key;
    value @1 :Value;
  }
}

error message:
Map.capnp:3:23: error: Parse error.

Environment: Ubuntu Kylin 14.04 , Cap'n Proto version 0.4.0

**Comment by dwrensha** [comment]
Hi!
Generics [were introduced](https://capnproto.org/news/2014-12-15-capnproto-0.5-generics-msvc-java-csharp.html) in version 0.5. You'll need to [install](https://capnproto.org/install.html) a more recent version of the schema compiler.
