### ISSUE TITLE
cyclic dependency

### ISSUE THREAD

**Issue by mtetreau** [sandstorm-io/capnproto#281]
Hi,

Is capnproto supposed to support definition schema cyclic dependency?

example:
```java
struct Animal
{
    union
    {
        cat @0 :Cat;
        dog @1 :Dog;
        mutant @2 Mutant;
    }
}

struct Cat
{
    species @0 :Text;
}

struct Dog
{
    species @0 :Text;
}

struct Mutant
{
    animals @0 :List(Animal);
}
```

Actually, it generates the compilation error:  Parse error.

Thanks!

**Comment by dwrensha** [comment]
Hi Marc,
The parse error is due to a missing colon. It should work if you edit the declaration of the `mutant` variant:

```
mutant @2 :Mutant;
```

**Comment by mtetreau** [comment]
Sorry my mistake!

However I still have an error when structs are defined in separate files:

animal.capnp:
```java
@0x810effbe021334ac;
using Java = import "/java.capnp";

using import "/com/peaktest/two/cat.capnp".CatStruct;
using import "/com/peaktest/two/dog.capnp".DogStruct;
using import "/com/peaktest/two/mutant.capnp".MutantStruct;

$Java.package("com.peaktest.two");
$Java.outerClassname("AnimalCapnp");

struct AnimalStruct
{
    union
    {
        cat @0 :CatStruct;
        dog @1 :DogStruct;
        mutant @2 :MutantStruct;
    }
}
```

cat.capnp:
```java
@0xf72d5ee77985261d;
using Java = import "/java.capnp";

$Java.package("com.peaktest.two");
$Java.outerClassname("CatCapnp");

struct CatStruct
{
    species @0 :Text;
}
```

dog.capnp:
```java
@0xe3c479eeb2d4556f;
using Java = import "/java.capnp";

$Java.package("com.peaktest.two");
$Java.outerClassname("DogCapnp");

struct DogStruct
{
    species @0 :Text;
}
```

mutant.capnp:
```java
@0xeb0a0c1a4d7f2056;
using Java = import "/java.capnp";

using import "/com/peaktest/two/animal.capnp".AnimalStruct;

$Java.package("com.peaktest.two");
$Java.outerClassname("MutantCapnp");

struct MutantStruct
{
    species @0 :Text;
    animals @1 :List(AnimalStruct);
}
```

which generates compilation error:
.../animal.capnp:1:1: error: Duplicate ID @0x810effbe021334ac.
com/peaktest/two/animal.capnp:1:1: error: ID @0x810effbe021334ac originally used here.

**Comment by kentonv** [comment]
The duplicate ID error probably has to do with the way you are invoking the capnp tool -- it looks like it isn't recognizing that "../animal.capnp" and "/com/peaktest/two/animal.capnp" refer to the same file, so it's parsing the same file twice, and then it sees that they have duplicate IDs. Probably this can be fixed by changing your invocation of capnp -- please tell us what your command line looks like now and we can show you how to fix it.

With that said, Cap'n Proto does not support mutually-dependent files. If you have mutually-dependent types, they must be placed in the same file. This is in part because some programming languages do not support mutually-dependent modules, so mutually-dependent capnp files would not work in those languages.

**Comment by mtetreau** [comment]
Actually we are compiling each schema file with its own capnp command:

```java
capnp compile --verbose -ojavaplugin/linux/x64/capnpc-java:target/generated-sources/capnp -Icapnp/javaplugin -Isrc/main/capnp/schema com/peaktest/two/cat.capnp
capnp compile --verbose -ojavaplugin/linux/x64/capnpc-java:target/generated-sources/capnp -Icapnp/javaplugin -Isrc/main/capnp/schema com/peaktest/two/dog.capnp
capnp compile --verbose -ojavaplugin/linux/x64/capnpc-java:target/generated-sources/capnp -Icapnp/javaplugin -Isrc/main/capnp/schema com/peaktest/two/animal.capnp
capnp compile --verbose -ojavaplugin/linux/x64/capnpc-java:target/generated-sources/capnp -Icapnp/javaplugin -Isrc/main/capnp/schema com/peaktest/two/mutant.capnp
```

We ended up like this after having some problems with a unique compiler call. 

Is it a good pratice?
