### ISSUE TITLE
Comparison of Cap'nProto to MPI?

### ISSUE THREAD

**Issue by webmaven** [sandstorm-io/capnproto#283]
I have seen many comparisons to protobufs (obviously), and thrift, etc., but none to [MPI](https://en.wikipedia.org/wiki/Message_Passing_Interface).

Could such a comparison be added to the documentation?

**Comment by kentonv** [comment]
Unfortunately I don't know anything about MPI. It looks like I'd need to spend a day or two studying it in order to produce a fair comparison, which is time I sadly don't have right now. :/

If someone from the community would like to write something up I'd be happy to review.

**Comment by kentonv** [comment]
(Closing because this isn't an actionable issue in Cap'n Proto.)
