### ISSUE TITLE
Add method to clear kj::Vector

### ISSUE THREAD

**Issue by katreniak** [sandstorm-io/capnproto#292]
kj::ArrayBuilder has method `operator=(decltype(nullptr))` to clear it.

The only way to clear kj::Vector I found is to assign default constructed Vector. But that is ugly to type.
Method `.resize(0)` requires T to have default constructor.

**Comment by kentonv** [comment]
I'm OK with either `= nullptr` or `.clear()`. I could also imagine a `truncate(n)` method that can only be used to reduce the size and doesn't require a default constructor.
