### ISSUE TITLE
CAPNP_HEADER_WARNINGS and -Wundef

### ISSUE THREAD

**Issue by liamstask** [sandstorm-io/capnproto#304]
When not installed to the system include directory and `-Wundef` is set for client code, `#if defined(__GNUC__) && !CAPNP_HEADER_WARNINGS`, which is included in a variety of installed headers, triggers compilation warnings.

Would you be interested in a patch that checks that `CAPNP_HEADER_WARNINGS` is defined?

**Comment by kentonv** [comment]
Ironic: The code which is supposed to squelch warnings produces a warning.

I would accept a patch changing all of the `!CAPNP_HEADER_WARNINGS` to `!defined(CAPNP_HEADER_WARNINGS)`.

**Comment by liamstask** [comment]
sounds good - can do :)
