### ISSUE TITLE
SONAME generation is strange

### ISSUE THREAD

**Issue by amluto** [sandstorm-io/capnproto#318]
capnproto does:

SONAME               libcapnp-0.5.3.so

normal practice is:

  SONAME               libz.so.1

Is there a reason that capnproto has the version before the .so instead of after it?  It confuses some automated package checking tools.

**Comment by kentonv** [comment]
Maintaining ABI compatibility between two versions of a C++ library is almost impossible, especially when templates are involved. Therefore, we use libtool's `-release` flag to shove the whole version number into SONAME.

https://github.com/sandstorm-io/capnproto/blob/master/c++/Makefile.am#L205

Although not widely used, this is a standard feature of libtool, so it surprises me that other tools would barf on it...

**Comment by kentonv** [comment]
I don't have any plans to change this for now, so I'm closing this bug. IMO it's a bug in other tools if they can't handle libtool's `-release` flag.

That said, I'm open to alternative proposals.
