### ISSUE TITLE
Support for installing shared object

### ISSUE THREAD

**Issue by tgockel** [sandstorm-io/capnproto#319]
The `kj` and `capnp` seem capable of building SOs, but when attempting to do so, there are issues with the `install` targets (`CMAKE_POSITION_INDEPENDENT_CODE` all works fine).

    $> cmake -DBUILD_SHARED_LIBS=1 -DCMAKE_POSITION_INDEPENDENT_CODE=1 ..

    CMake Error at src/kj/CMakeLists.txt:60 (install):
    install TARGETS given no LIBRARY DESTINATION for shared library target
    "kj".

    CMake Error at src/kj/CMakeLists.txt:76 (install):
    install TARGETS given no LIBRARY DESTINATION for shared library target
    "kj-test".

    CMake Error at src/kj/CMakeLists.txt:97 (install):
    install TARGETS given no LIBRARY DESTINATION for shared library target
    "kj-async".

    CMake Error at src/capnp/CMakeLists.txt:61 (install):
    install TARGETS given no LIBRARY DESTINATION for shared library target
    "capnp".

    CMake Error at src/capnp/CMakeLists.txt:93 (install):
    install TARGETS given no LIBRARY DESTINATION for shared library target
    "capnp-rpc".

    CMake Error at src/capnp/CMakeLists.txt:113 (install):
    install TARGETS given no LIBRARY DESTINATION for shared library target
    "capnp-json".

    CMake Error at src/capnp/CMakeLists.txt:134 (install):
    install TARGETS given no LIBRARY DESTINATION for shared library target
    "capnpc".

Or am I doing something wrong?

**Comment by katreniak** [comment]
Your command works for me with changed in this PR. 

````
[brano@brano-desk gen]$ cmake -DBUILD_SHARED_LIBS=1 -DCMAKE_POSITION_INDEPENDENT_CODE=1 ..
-- The CXX compiler identification is GNU 5.3.1
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include initializer_list
-- Looking for C++ include initializer_list - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/brano/src/capnproto/c++/gen
````

**Comment by tgockel** [comment]
Did you mean PR 314?

**Comment by katreniak** [comment]
Yes. https://github.com/sandstorm-io/capnproto/pull/314

**Comment by tgockel** [comment]
I tried that and it worked for me as well. Awesome :hamster:

**Comment by katreniak** [comment]
PR #314 was merged. Is this issue resolved now?

**Comment by tgockel** [comment]
Yup, works great.
