### ISSUE TITLE
checkCompiler.h

### ISSUE THREAD

**Issue by hernandezurbina** [sandstorm-io/capnproto#321]
Hi, I'm trying to find checkCompiler.h. Did you remove it?

**Comment by kentonv** [comment]
I don't think we ever had a file with that name in this repo, but maybe you're talking about this file from pycapnp?

https://github.com/jparyani/pycapnp/blob/develop/capnp/helpers/checkCompiler.h

**Comment by hernandezurbina** [comment]
yes, I think you're right! I'll have a look. Thanks!
