### ISSUE TITLE
Compilation error on Visual Studio 2015 (master branch only)

### ISSUE THREAD

**Issue by frol** [sandstorm-io/capnproto#324]
```
error C2668: 'capnp::_::kindSfinae': ambiguous call to overloaded function [C:\Miniconda\conda-bld\work\capnproto-master\build\src\capnp\capnp.vcxproj]
  c:\miniconda\conda-bld\work\capnproto-master\c++\src\capnp\common.h(133): note: could be 'uint64_t capnp::_::kindSfinae<T>(...)'
          with
          [
              T=unknown-type
          ]
  c:\miniconda\conda-bld\work\capnproto-master\c++\src\capnp\common.h(131): note: or       'uint16_t capnp::_::kindSfinae<T,T::_capnpPrivate::IsInterface>(int)'
          with
          [
              T=unknown-type
          ]
  c:\miniconda\conda-bld\work\capnproto-master\c++\src\capnp\common.h(130): note: or       'uint8_t capnp::_::kindSfinae<T,T::_capnpPrivate::IsStruct>(int)'
          with
          [
              T=unknown-type
          ]
  c:\miniconda\conda-bld\work\capnproto-master\c++\src\capnp\common.h(138): note: while trying to match the argument list '(int)'
  c:\miniconda\conda-bld\work\capnproto-master\c++\src\capnp\any.h(455): note: see reference to class template instantiation 'capnp::_::MsvcWorkaround<T>' being compiled
          with
          [
              T=unknown-type
          ]
c:\miniconda\conda-bld\work\capnproto-master\c++\src\capnp\common.h(138): error C2056: illegal expression [C:\Miniconda\conda-bld\work\capnproto-master\build\src\capnp\capnp.vcxproj]
  blob.c++
  arena.c++
```

The full log is available here: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.1944/job/tr80nn04u04qufj1

Compilation commands:

```
> cd build
> cmake ^
    -G"Visual Studio 14 2015" ^
    -DCAPNP_LITE=ON ^
    -DBUILD_TESTING=OFF ^
    -DCMAKE_INSTALL_PREFIX=C:\Miniconda\envs\_build\Library ^
    ..\c++
> cmake --build . --config Release
```

NOTE: 0.5.3 release compiles just fine.

**Comment by frol** [comment]
@pqu You have said that you have tested #314 on MSVC. Do you have an idea what is going on here?

**Comment by pqu** [comment]
I only tested it insofar as CMake produced a reasonable Visual Studio project, but it did not successfully compile. It looks like `master` has slipped out of sync with what MSVC supports.

**Comment by kentonv** [comment]
Sorry, but nearly all Cap'n Proto development happens in conjunction with the Sandstorm project which is very much Linux-based, and keeping everything working on MSVC as we go is infeasible (we don't even have any Windows machines here). You'll need to work from a release version if you're on MSVC (but using a release version is a good idea anyway). We'll get MSVC working again before the next release. (In fact, @harrishancock has been working on it.)

**Comment by frol** [comment]
I also target Linux myself, but I had been [packaging Cap'n Proto](https://github.com/conda-forge/capnproto-feedstock/) for [Anaconda](https://www.continuum.io/why-anaconda) repository, so I just tried to build master branch on Windows for the sake of experiment and reported the issue I got.
