### ISSUE TITLE
Generated method asGeneric is broken for Inner template classes.

### ISSUE THREAD

**Issue by katreniak** [sandstorm-io/capnproto#334]
Capnp declaration:
````cpp
struct TestGenerics(Foo, Bar) {
  struct Inner {
    foo @0 :Foo;
    bar @1 :Bar;
  }
````

Generated header:
````cpp
template <typename Foo, typename Bar>
class TestGenerics<Foo, Bar>::Inner::Builder {
public:
    typename Inner::Builder asGeneric() {
    return typename Inner::Builder(_builder);
  }
````

The generated code should look like this:
````cpp
template <typename Foo, typename Bar>
class TestGenerics<Foo, Bar>::Inner::Builder {
public:
  template <typename Foo2 = ::capnp::AnyPointer, typename Bar2 = ::capnp::AnyPointer>
  typename TestGenerics<Foo2, Bar2>::Builder asGeneric() {
    return typename TestGenerics<Foo2, Bar2>::Inner::Builder(_builder);
  }
````

Call to `node.getParameters()` on `Inner` node in `capnp-c++.c++` returns empty list . I believe that this is incorrect and `NodeTranslator::compileNode` in `node-translator.c++` should add parameters from parent scopes into node parameters.

Any hints?

**Comment by kentonv** [comment]
`Node.parameters` is working as intended -- you need to follow `scopeId` to the parent scope to discover if it has parameters too.

I see what you mean about `asGeneric()`, though. The tricky question is what do you do if both `TestGenerics` and `TestGenerics::Inner` have type parameters? Does `asGeneric()` concatenate them into its own type parameter list? The problem there is that it's intended that you can add new type parameters to the end of the list without breaking source compatibility, but if we're concatenating them then adding parameters to the parent will change the offset of the child parameters, breaking things.

Maybe we need a separate method to re-assign each of the parent scopes.

    innerBuilder.asTestGenerics<MyFoo, MyBar>()

**Comment by katreniak** [comment]
Thank you for great explanation. I believed that I am walking wrong path.

I like your API proposal. I would like to align on more details:

````cpp
struct Outer(T1) {
  struct Middle(T2) {
    struct Inner(T3) {
      t1 @0 :T1;
      t2 @1 :T2;
      t3 @2 :T3;
    }
  }
}
````

Generated code:
````cpp
template <typename T32 = ::capnp::AnyPointer>
typename Inner<T32>::Reader asGeneric() {..}

template <typename T22 = ::capnp::AnyPointer, 
typename T32 = ::capnp::AnyPointer>
typename Middle<T22>::template Inner<T32>::Reader asMiddleGeneric() {..}

template <typename T12 = ::capnp::AnyPointer,
template <typename T22 = ::capnp::AnyPointer,
template <typename T32 = ::capnp::AnyPointer>
typename Outer<T12>::template Middle<T22>::template Inner<T32>::Reader asOuterMiddleGeneric() {..}
````

Does it makes sense to generate `asXyzGeneric` for template scopes that have zero arguments as current code is doing?

````cpp
struct Outer(T1) {
    struct Inner {
      t1 @0 :T1;
  }
````

Generated code:
````cpp
typename Outer<T12>::Reader asGeneric() {..} // remove?

template <typename T12 = ::capnp::AnyPointer>
typename Outer<T12>::Inner::Reader asOuterGeneric() {..}
````

What is the correct way to get the parent template name in `TemplateContext` in `capnp-c++.c++`? I discovered only this: `node.getDisplayName().slice(node.getDisplayNamePrefixLength())`.

**Comment by kentonv** [comment]
I was thinking rather:

    template <typename T32 = ::capnp::AnyPointer>
    typename Inner<T32>::Reader asGeneric() {..}

    template <typename T22 = ::capnp::AnyPointer>
    typename Middle<T22>::template Inner<T3>::Reader asMiddleGeneric() {..}

    template <typename T12 = ::capnp::AnyPointer>
    typename Outer<T12>::template Middle<T2>::template Inner<T3>::Reader asOuterGeneric() {..}

That is to say, each of these methods only modifies the type parameters for one type. If you need to modify type parameters at multiple levels, you might end up with something like:

    reader.asOuterGeneric<Foo>().asMiddleGeneric<Bar>().asGeneric<Baz>()

This way we never concatenate multiple type parameter lists into a single list and thus never create compatibility problems when new types are appended to the outer type parameter lists.

I think there's no need to generate these methods in cases where they would have zero type parameters.

The way to get the parent is by following `Node.scopeId`. See, for example, the code that generates a fully-qualified type name:

https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/compiler/capnpc-c++.c++#L320

**Comment by katreniak** [comment]
Works for me.
