### ISSUE TITLE
dynamic api cannot pipeline on result of type `Type::anyPointer::unconstrained::Capability`

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/capnproto#336]
In the [Sandstorm Python test app](https://github.com/zarvox/sandstorm-test-python), I would like to be able to call [`SandstormApi.restore()`](https://github.com/sandstorm-io/sandstorm/blob/v0.164/src/sandstorm/grain.capnp#L285) and then pipeline on `cap` field in the results. However, attempting to do so triggers [this error](https://github.com/sandstorm-io/capnproto/blob/94946a097db0d61118be7229d8b0bb8b8d448147/c%2B%2B/src/capnp/dynamic.c%2B%2B#L387).

**Comment by kentonv** [comment]
Yeah, the switch probably needs cases for the "any" types -- `AnyStruct` and `Capability`, specifically.
