### ISSUE TITLE
Tests fail to build when exceptions are disabled

### ISSUE THREAD

**Issue by debrouxl** [sandstorm-io/capnproto#340]
As of 0fb92820af3c9f31117081b3c08e01066e07ed55, when exceptions are disabled (yeah, some weirdos like me and my colleagues do that ^^), the library's code builds correctly, but 11 tests fail to build with errors such as:
src/kj/common-test.c++:225:75: error: 'EXPECT_DEATH_IF_SUPPORTED' was not declared in this scope

The other tests whose build fails, because EXPECT_DEATH_IF_SUPPORTED or EXPECT_DEATH are not declared, are:
src/kj/exception-test.c++
src/kj/mutex-test.c++
src/capnp/encoding-test.c++
src/capnp/orphan-test.c++
src/capnp/test-util.c++
src/kj/async-test.c++
src/capnp/capability-test.c++
src/capnp/schema-loader-test.c++
src/capnp/dynamic-test.c++
src/capnp/rpc-twoparty-test.c++

Tested with CXXFLAGS='-std=c++14 -fno-exceptions' on Debian Jessie amd64 (g++ 4.9) and Debian sid amd64 (g++ 5.4), but the issue is platform-agnostic.
With the same CXXFLAGS, the Jessie amd64 environment successfully builds the 0.5.3 library+tests, and the tests pass.

**Comment by kentonv** [comment]
Hi Lionel,

We don't recommend using Cap'n Proto from git master unless you're specifically working with Cap'n Proto's parent project, Sandstorm.io. Release builds of Cap'n Proto are tested with every permutation of compiler flags and target platforms, but between releases we only target the specific needs of Sandstorm, namely: Linux, Clang, C++14, exceptions+RTTI enabled. We can't make any promises about other targets in the meantime, unless someone is volunteering to help maintain them.

**Comment by kentonv** [comment]
Closing because this will be fixed for the 0.6 release and in general testing with -fno-exceptions is part of our release process.
