### ISSUE TITLE
List<T>::operator Reader / List<T>::asReader should be const

### ISSUE THREAD

**Issue by ecatmur** [sandstorm-io/capnproto#349]
ex. https://github.com/sandstorm-io/capnproto/blob/master/c%2B%2B/src/capnp/list.h#L146

    inline operator Reader() { return Reader(builder.asReader()); }
    inline Reader asReader() { return Reader(builder.asReader()); }

These could/should be const, since `_::ListBuilder::asReader` is const, as are all other `asReader` methods (incl. generated). Sites to fix are 4 specializations in list.h, and one in capability.h.

**Comment by kentonv** [comment]
I agree. Want to send a PR? :)

**Comment by ecatmur** [comment]
Done, sorry for the delay.

Passes make check.
