### ISSUE TITLE
PointerBuilder & PointerReader capability

### ISSUE THREAD

**Issue by diorcety** [sandstorm-io/capnproto#355]
Hi,
I'm using capnproto over another RPC communication system. I succeed to avoid to modify capnproto for a such usage, but i'm stuck now on some "minor" point.
There is really one tricky point, it's about capability in the PointerBuilder and PointerBuilder.
You are using capability in order to "propagate" some context in the builder, which is used with interface kind. But the point is that this use _ClientHook class, which is specific to your rpc system. When the client inject itself in the builder (rpc side), the capnp side has no need to know the real "implementation" of the capability.

**Comment by kentonv** [comment]
I'm sorry, I don't understand the question.

Is your alternate RPC system an object-capability system or is it traditional first-order RPC? If it's first-order (as most other RPC systems are these days) then you should be able to safely ignore all the ClientHook stuff.

**Comment by diorcety** [comment]
The clienthook allow the interface builder to recreate a client object for this interface. My point is that the hightly tie between this client hook(where only addref and isNull are user by non RPC code) with the capnp RPC, is the only object which block to use another RPC system with the full capnproto schema capacity(Using interface as argument or membre)

**Comment by diorcety** [comment]
I created a custom compiler using my own client and server implementation. It works great. I was starting to add the interface as argument "feature", when i fall on this client hook usage un the builder/reader.(capability). For me un this part this capability is more a cookie keeped as RPC context. M'y point is to make this cookie abstract, un ordre to really split capnp and capnp RPC.

**Comment by kentonv** [comment]
ClientHook is not specific to Cap'n Proto's RPC system. It's an abstract interface which you can implement in whatever way is appropriate for your own RPC system. If you want to implement an alternate RPC system that supports capabilities (remote object references carried in messages), then you will need to implement ClientHook.

**Comment by diorcety** [comment]
My schema generated api is totaly different from the original one. I didn't want use capnp clienthook. This is finally not really the point. The point is that you need pass context through reader/builder. You use capability factory for storing this context (which is ClientHook). The issue is that the reader/builder depend on RPC only for this context stuff without the need to know what is beneath it. If i can quote the layout.c++

    // Horrible hack:  We need to be able to construct broken caps without any capability context,
    // but we can't have a link-time dependency on libcapnp-rpc.

**Comment by diorcety** [comment]
I'm finally manage to "contextualize" my reader/builder using capTablePointer, pointing to something different. Very hacky but working. I'm closing the issue but i'm still thinking that builder/reader should be not aware of capability implementation details.

**Comment by kentonv** [comment]
I think there's some confusion here between "capability implementation details" and "RPC implementation details".

The Cap'n Proto library can be adapted to work with alternate RPC implementations. That is, if you invented a new RPC protocol, you could plug it in by implementing your own subclasses of the types defined in `capnp/capability.h`.

But the Cap'n Proto library is very much coupled to a single design for "capabilities", using the KJ event loop, promises, and a particular interface design.

There's no getting around this. In Cap'n Proto, a struct can contain a field whose type is an interface -- an object reference. This means that the implementation of structs needs to know how to manipulate these references. ClientHook is one of the abstract types that is used for this purpose.

You can't separate structs from interfaces any more than you can separate structs from lists or enums. These things all need to work together. If you don't like how capabilities are represented in the current implementation, your best bet is probably to fork it or write your own from scratch. Sorry.

**Comment by diorcety** [comment]
I'm agreed with what you said. I'm not trying to make capnproto change. I'm just pointing a thing in the code, which is for me seems to be a bad disgn, that i discovered when trying to implement another RPC. Does Reader/Builder need to know about capability? I'm pretty sure no, it's not mandatory, it seems to done that way in order to simplify the coding. The CapTable, brokenCapFactory  and ClientHook in Reader/Builder are only used to associate the Capability context when using capability. There is no need in Reader/Builder to know that ClientHook has "kj::Promise<void> whenResolved();", function. The only need is to create a new reference with "virtual kj::Own<ClientHook> addRef() = 0;" to transfer the context until Capability code get it back.

**Comment by kentonv** [comment]
Yes, Readers/Builders need to know about capabilities. My previous comment explains this.

**Comment by diorcety** [comment]
Okay, i just no know where in Readers/Builders code, it use something else that addRef/isNull function. I'm saying that because before finding my hacky solution with captable, I created a base ClientHook class used by Reader/Builders (extended by ClientHook), containing only isNull and addRef ... with few changes (casting on rpc side), it works well ... I can send you the diff if you want. My point is, yes reader/builder need to know about capabilities, but they didn't have to know the implementation. Anyway it seems to be a dead end. Thanks
