### ISSUE TITLE
[schema] unconfirmed undefined behavior

### ISSUE THREAD

**Issue by bryongloden** [sandstorm-io/capnproto#360]
Greetings. On line numbers `879-881` of [c++/src/capnp/schema.h](https://github.com/sandstorm-io/capnproto/blob/master/c%2B%2B/src/capnp/schema.h#L879) it appears that member variable '`anyPointerKind`' is initialized by itself. If so, it is undefined behavior. Can somebody else confirm or rebut it? Thank you.

**Comment by johnkingsley** [comment]
I think the code is fine.

It is defined behaviour in C++. See http://eel.is/c++draft/class.base.init#15

**Comment by kentonv** [comment]
Hi @bryongloden,

The member is not initialized to itself. It is initialized to the constructor's parameter, which happens to have the same name. So, there's no issue here AFAICT.

Thanks for checking!
