### ISSUE TITLE
Allow `= null` in interface method parameter lists

### ISSUE THREAD

**Issue by zombiezen** [sandstorm-io/capnproto#363]
If you declare an interface like this:

``` capnp
interface Foo {
  frobulate @0 (x :Int32, y :Int32 = 42) -> (answer :Int32);
}
```

and later you want to add an optional Bar capability, I don't think there's a valid token I can place here:

``` capnp
interface Foo {
  frobulate @0 (x :Int32, y :Int32 = 42, bar :Bar = ????) -> (answer :Int32);
}

interface Bar {
}
```

One workaround is to convert the parameter list to an explicit struct.  There's some complexity in determining the type ID of the existing parameter list, but it is doable.  However, this usually changes the existing generated code.

**Comment by dwrensha** [comment]
What do you want the default value of `bar` to be? If the answer is `null` then I think it should work to not specify a default:

```capnp
interface Foo {
  frobulate @0 (x :Int32, y :Int32 = 42, bar :Bar) -> (answer :Int32);
}
```

**Comment by zombiezen** [comment]
I would like it to be null, my concern is that [Evolving your Protocol](https://capnproto.org/language.html#evolving-your-protocol) states that:

> New parameters may be added to a method. The new parameters must be added to the end of the parameter list and **must have default values**.

(Emphasis mine.)  I don't think I can set a default value here.

**Comment by kentonv** [comment]
Ah, right. I believe we enforce that if one parameter has a default, all following parameters must also have defaults. The idea is that usually some of the parameters are in fact required, and in languages where the parameters are passed positionally we should go ahead and force the caller to provide values for those parameters.

Probably the parser should grow support for writing `= null`, maybe specifically in the context of parameters.

I also kind of want to extend the language with a concept of `Maybe(T)`...

**Comment by dwrensha** [comment]
> I believe we enforce that if one parameter has a default, all following parameters must also have defaults. 

Nope. For example, `capnp compile` does not throw an error on the following:

```capnp
struct Foo { word @0 :Text; }

interface Bar {}

interface Baz {
   baz @0 (a :Int32 = 10, b :Int16, c :Bar, d :Foo = (word = "hi"), e :Bar) -> ();
}
```

>  The idea is that usually some of the parameters are in fact required, and in languages where the parameters are passed positionally we should go ahead and force the caller to provide values for those parameters.

I'm struggling to understand what you mean here. What do parameter defaults have to do with forcing the caller to provide a value? If anything, they allow the caller to get away with omitting a value.

More fundamentally, though, every type in Cap'n Proto already has a default value. All that a parameter default does is to override that implicit default. It sounds like you're arguing that in some cases we should enforce explicitness, but I don't see what that buys us.

**Comment by kentonv** [comment]
> I'm struggling to understand what you mean here. What do parameter defaults have to do with forcing the caller to provide a value? If anything, they allow the caller to get away with omitting a value.

I mean that the parameters that _don't_ have a default are required.

> It sounds like you're arguing that in some cases we should enforce explicitness, but I don't see what that buys us.

If there's a method:

    multiply @0 (a :Float32, b :Float32) -> (result :Float32);

And I call it like:

    calculator.multiply(12)

I think my compiler should complain that I forgot the second argument.

**Comment by dwrensha** [comment]
Ah, I see. That makes sense and matches how default parameters work in Python, for example.

However, I'm still confused about why new parameters are supposed to have defaults. I thought the [Evolve Your Protocol](https://capnproto.org/language.html#evolving-your-protocol) requirements were only concerned with wire compatibility, but the requirement about new parameters requiring explicit defaults seems to be a code-compatibility concern.

**Comment by kentonv** [comment]
@dwrensha Ah. Yes, I think you're right: I mixed up types of compatibility there.

**Comment by kaos** [comment]
> Probably the parser should grow support for writing = null, maybe specifically in the context of parameters.

Yes, please :) 👍

**Comment by zombiezen** [comment]
Hit this again and updated the title.  The problem is not unique to capabilities: it would be ideal for other pointer types.  Kenton is right that the concern is just for parameter lists.
