### ISSUE TITLE
ForkedPromise lifetime

### ISSUE THREAD

**Issue by barakp** [sandstorm-io/capnproto#367]
Hi @kentonv
Could you kindly help understand what's the lifetime of a ForkedPromise object? would it be destructed upon fulfilment? upon getting out of scope? upon assigning a nullptr? upon assigning a new (other)  #ForkedPromise?

Thanks!

**Comment by kentonv** [comment]
Hi @barakp,

ForkedPromise is reference counted -- each branch (created with `addBranch()`) holds a reference. If you destroy all the branches (and let the `ForkedPromise` itself go out-of-scope) then the promise will be canceled, but not otherwise.
