### ISSUE TITLE
How to join promises?

### ISSUE THREAD

**Issue by szenker** [sandstorm-io/capnproto#371]
In my application, I'm doing something like the following ...

```

class MyAdapter;

kj::Promise<void> g()
{
	return newAdaptedPromise<void, MyAdapter>();
}

kj::Promise<void> f()
{
	auto builder = kj::heapArrayBuilder<kj::Promise<void>>(100);
	for (...)
	{
		builder.add(g());
	}
	return kj::joinPromises(builder.finish());
}

...

f().then([]()
{
	printf("all completed\n");
}).detach([](kj::Exception&&){});

```

When debugging this application, the dtor of all MyAdapter instances get called when leaving the scope of f(). How is the ownership of the adapters managed (kj::newAdaptedPromise)? How can I join promises "correctly"? What I want is, that f() returns one promise which gets fulfilled as soon as all promises produced within the for-loop are fulfilled.

Thanks
Sebastian

**Comment by kentonv** [comment]
Hmm, the dtor of each MyAdapter instance should not be called until the promise it implements either completes or is canceled. So, what you describe sounds like a bug. But I would think such a bug would have broken a lot of things.

Could you write a minimal self-contained test case that I can build and run demonstrating this problem? Then I'd be happy to debug it.

**Comment by szenker** [comment]
I created the following test case and (you are right) it isn't a bug in kj framework. Actually, I found out, that my application was buggy. I was calling `builder.finish()` before I added all promises to the array. This throws an exception, which was not correctly handled in my application.

In case I don't know ahead how many promises I need to join but I know the maximum number of promises: is it a good approach to use `kj::joinPromises(calls.releaseAsArray())`?

```
class MyAdapter {
  private:
  PromiseFulfiller<void>& fulfiller;
  Promise<void> promise;

  public:
  MyAdapter(PromiseFulfiller<void>& f) :
    fulfiller(f),
    promise(evalLater([this]() {
      fulfiller.fulfill();
    }).eagerlyEvaluate(nullptr)) {
  }
};

Promise<void> g()
{
  return newAdaptedPromise<void, MyAdapter>();
}

Promise<void> f()
{
  auto builder = heapArrayBuilder<Promise<void>>(3);
  builder.add(g());
  builder.add(g());
  builder.add(g());
  return joinPromises(builder.finish());
}

TEST(Async, ArrayJoinAdapters) {
  EventLoop loop;
  WaitScope waitScope(loop);

  Promise<void> promise = f();
  promise.wait(waitScope);
}
```

**Comment by kentonv** [comment]
Yes, you can use a `kj::Vector` and `.releaseAsArray()` for cases where you don't know how much space to allocate in advance. Note that `.releaseAsArray()` will make a copy (moving all elements) if the vector backing store doesn't happen to be exactly the right size. But probably this kind of micro-optimization doesn't usually matter.
