### ISSUE TITLE
./super_test.sh compile error, macOS 10.12, llvm 8.0

### ISSUE THREAD

**Issue by liketemple** [sandstorm-io/capnproto#372]
In file included from ./src/capnp/generated-header-support.h:31:
**./src/capnp/layout.h:660:36: error: field 'elementSize' will be initialized after field 'structDataSize'
      [-Werror,-Wreorder]
        step(0 * BITS / ELEMENTS), elementSize(elementSize), structDataSize(0 * BITS),
                                   ^**
In file included from src/capnp/compiler/capnpc-c++.c++:24:
In file included from ./src/capnp/schema.capnp.h:7:
In file included from ./src/capnp/generated-header-support.h:31:
**./src/capnp/layout.h:660:36: error: field 'elementSize' will be initialized after field 'structDataSize'
      [-Werror,-Wreorder]
        step(0 * BITS / ELEMENTS), elementSize(elementSize), structDataSize(0 * BITS),
                                   ^**
In file included from src/capnp/compiler/capnp.c++:22:
In file included from src/capnp/compiler/lexer.h:29:
In file included from ./src/capnp/compiler/lexer.capnp.h:7:
In file included from ./src/capnp/generated-header-support.h:31:
**./src/capnp/layout.h:660:36: error: field 'elementSize' will be initialized after field 'structDataSize'
      [-Werror,-Wreorder]
        step(0 * BITS / ELEMENTS), elementSize(elementSize), structDataSize(0 * BITS),
                                   ^**
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/Users/like/gitsrc/capnproto/tmp-staging/include\" -D_THREAD_SAFE -O2 -DDEBUG -Wall -Wextra -Werror -Wno-strict-aliasing -Wno-sign-compare -Wno-unused-parameter -Wno-error=unused-command-line-argument -D_THREAD_SAFE -MT src/capnp/compiler/md5.lo -MD -MP -MF src/capnp/compiler/.deps/md5.Tpo -c src/capnp/compiler/md5.c++  -fno-common -DPIC -o src/capnp/compiler/.libs/md5.o
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/Users/like/gitsrc/capnproto/tmp-staging/include\" -D_THREAD_SAFE -O2 -DDEBUG -Wall -Wextra -Werror -Wno-strict-aliasing -Wno-sign-compare -Wno-unused-parameter -Wno-error=unused-command-line-argument -D_THREAD_SAFE -MT src/capnp/compiler/error-reporter.lo -MD -MP -MF src/capnp/compiler/.deps/error-reporter.Tpo -c src/capnp/compiler/error-reporter.c++  -fno-common -DPIC -o src/capnp/compiler/.libs/error-reporter.o
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/Users/like/gitsrc/capnproto/tmp-staging/include\" -D_THREAD_SAFE -O2 -DDEBUG -Wall -Wextra -Werror -Wno-strict-aliasing -Wno-sign-compare -Wno-unused-parameter -Wno-error=unused-command-line-argument -D_THREAD_SAFE -MT src/capnp/compiler/lexer.capnp.lo -MD -MP -MF src/capnp/compiler/.deps/lexer.capnp.Tpo -c src/capnp/compiler/lexer.capnp.c++  -fno-common -DPIC -o src/capnp/compiler/.libs/lexer.capnp.o
In file included from src/capnp/compiler/lexer.capnp.c++:4:
In file included from src/capnp/compiler/lexer.capnp.h:7:
In file included from ./src/capnp/generated-header-support.h:31:
**./src/capnp/layout.h:660:36: error: field 'elementSize' will be initialized after field 'structDataSize'
      [-Werror,-Wreorder]
        step(0 * BITS / ELEMENTS), elementSize(elementSize), structDataSize(0 * BITS),
                                   ^**
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/Users/like/gitsrc/capnproto/tmp-staging/include\" -D_THREAD_SAFE -O2 -DDEBUG -Wall -Wextra -Werror -Wno-strict-aliasing -Wno-sign-compare -Wno-unused-parameter -Wno-error=unused-command-line-argument -D_THREAD_SAFE -MT src/capnp/compiler/error-reporter.lo -MD -MP -MF src/capnp/compiler/.deps/error-reporter.Tpo -c src/capnp/compiler/error-reporter.c++ -o src/capnp/compiler/error-reporter.o >/dev/null 2>&1
1 error generated.
make: *** [src/capnp/compiler/lexer.capnp.lo] Error 1
make: *** Waiting for unfinished jobs....
libtool: compile:  clang++ -std=gnu++11 -DHAVE_CONFIG_H -I. -I./src -I./src -DKJ_HEADER_WARNINGS -DCAPNP_HEADER_WARNINGS -DCAPNP_INCLUDE_DIR=\"/Users/like/gitsrc/capnproto/tmp-staging/include\" -D_THREAD_SAFE -O2 -DDEBUG -Wall -Wextra -Werror -Wno-strict-aliasing -Wno-sign-compare -Wno-unused-parameter -Wno-error=unused-command-line-argument -D_THREAD_SAFE -MT src/capnp/compiler/md5.lo -MD -MP -MF src/capnp/compiler/.deps/md5.Tpo -c src/capnp/compiler/md5.c++ -o src/capnp/compiler/md5.o >/dev/null 2>&1
1 error generated.
make: *** [src/capnp/compiler/module-loader.o] Error 1
In file included from src/capnp/compiler/capnp.c++:22:
In file included from src/capnp/compiler/lexer.h:29:
In file included from ./src/capnp/compiler/lexer.capnp.h:7:
In file included from ./src/capnp/generated-header-support.h:31:
In file included from ./src/capnp/layout.h:37:
**./src/kj/parse/../memory.h:79:5: error: destructor called on non-final 'capnp::compiler::Compiler' that has virtual
      functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    reinterpret_cast<T*>(pointer)->~T();
    ^**
./src/kj/parse/../memory.h:84:71: note: in instantiation of member function
      'kj::DestructorOnlyDisposer<capnp::compiler::Compiler>::disposeImpl' requested here
const DestructorOnlyDisposer<T> DestructorOnlyDisposer<T>::instance = DestructorOnlyDisposer<T>();
                                                                      ^
./src/kj/parse/../memory.h:369:54: note: in instantiation of static data member
      'kj::DestructorOnlyDisposer<capnp::compiler::Compiler>::instance' requested here
    return Own<T>(&value, DestructorOnlyDisposer<T>::instance);
                                                     ^
src/capnp/compiler/capnp.c++:282:32: note: in instantiation of function template specialization
      'kj::SpaceFor<capnp::compiler::Compiler>::construct<capnp::compiler::Compiler::AnnotationFlag &>' requested here
      compiler = compilerSpace.construct(annotationFlag);
                               ^
./src/kj/parse/../memory.h:79:37: note: qualify call to silence this warning
    reinterpret_cast<T*>(pointer)->~T();
                                    ^
                                    capnp::compiler::Compiler::
2 errors generated.
make: *** [src/capnp/compiler/capnp.o] Error 1
1 error generated.
make: *** [src/capnp/compiler/capnpc-c++.o] Error 1

**Comment by dwrensha** [comment]
Thanks for the report. I've submitted a fix: https://github.com/sandstorm-io/capnproto/pull/373

**Comment by liketemple** [comment]
Thanks a lot!

**Comment by kentonv** [comment]
@liketemple Out of curiosity, why were you running super-test.sh? It's primarily intended for use by the maintainer (me) to do extended release validation. Generally users should use `make check` to run the tests.
