### ISSUE TITLE
brew install capnproto: capnproto-json.a missing?

### ISSUE THREAD

**Issue by seeekr** [sandstorm-io/capnproto#381]
Hi there!

I believe that there's an issue with the brew installation of capnp.

When I do a manual compilation from source I'm getting these libraries built:

```
$ls -1 *.a
libcapnp-json.a
libcapnp-rpc.a
libcapnp.a
libcapnpc.a
libkj-async.a
libkj-test.a
libkj.a
```

while when I look at what homebrew installed it is this:

```
$ls -1 /usr/local/Cellar/capnp/0.5.3/lib                    
libcapnp-rpc.a
libcapnp.a
libcapnpc.a
libkj-async.a
libkj.a
```

Aside from libkj-test.a which is probably a lib that's used only when running tests it seems like

`libcapnp-json.a`

is the one missing on my system.

I was originally alerted to this by the fact that the FindCapnProto.cmake script will not run on my system unless I specify:

`set(CAPNP_LIB_CAPNP-JSON "")`

(Error message then is just CMake complaining about the variable being `NOTFOUND`.)

If I'm just doing something wrong, please let me know. Otherwise it'd be great to get this issue fixed. I'd be happy to send a PR if I understood what's going wrong, but just from looking at the [brew formula](https://github.com/Homebrew/homebrew-core/blob/ba0aa68066a89c0654152aba22819736b06987af/Formula/capnp.rb) I couldn't figure that out.

Cheers,
Denis

**Comment by paulproteus** [comment]
Hi Denis,

The reason it's missing is that the git master contains JSON support but
the released version does not yet.

https://groups.google.com/forum/#!topic/capnproto/tQDI3DfJTrE contains some
more information about that.

I hope that helps! Thanks for asking the question and for your patience.

**Comment by seeekr** [comment]
Oh god -- that thought should have crossed my mind, but it didn't. :)

Thanks for clarifying! I'll close the issue then since there's nothing really actionable here, other than potentially linking to the latest release-compatible FindCapnProto.cmake file from somewhere in the docs to avoid potential for confusion?
