### ISSUE TITLE
encapsulated types and graph support

### ISSUE THREAD

**Issue by jwaterloo** [sandstorm-io/capnproto#385]
Concerning Near-ish future

"Implement encapsulated types: This will allow you to create a hand-written wrapper around a type which will be automatically injected into the generated code, so that you can provide a nicer interface which encapsulates the type’s inner state."

Will the design support encapsulating more than one field, such that a graph gets serialized as node list, edge list and entry point list.

If so this could open up graph support.

**Comment by kentonv** [comment]
Yes, encapsulation would apply to types, not to fields, so you could encapsulate your `Graph` type.

Closing this since it's seemingly a question rather than an action item. Feel free to e-mail the mailing list for open discussions: https://groups.google.com/group/capnproto
