### ISSUE TITLE
Promise cancellation and PromiseFulfillerPair

### ISSUE THREAD

**Issue by barakp** [sandstorm-io/capnproto#392]
Hi @kentonv,

What would be the expected outcome of calling fulfiller->fulfill()/reject() on an already cancelled promise assuming both were created using `newPromiseAndFulfiller<T>`?
Also - in case this isn't a good practice - what would be the recommended usage when creating a promise to be returned to callers (or even forked and branched out to users)? is using newPromiseAndFulfiller safe in that manner?

Thanks,
Barak

**Comment by kentonv** [comment]
> What would be the expected outcome of calling fulfiller->fulfill()/reject() on an already cancelled promise assuming both were created using newPromiseAndFulfiller<T>?

There would be no effect. The function will return normally but the value / exception would be discarded.

> Also - in case this isn't a good practice - what would be the recommended usage when creating a promise to be returned to callers (or even forked and branched out to users)? is using newPromiseAndFulfiller safe in that manner?

Generally if you have a use case that seems to call for newPromiseAndFulfiller, then it's probably the right thing to do. :)
