### ISSUE TITLE
canonicalize() throws on empty message (c++)

### ISSUE THREAD

**Issue by sasha-s** [sandstorm-io/capnproto#394]
This code:
```c++
  MallocMessageBuilder message;
  auto msg = message.initRoot<msg::Ints>();
  msg.setElt(0);
  canonicalize(msg.asReader());
```
throws 
```
kj::ExceptionImpl: capnp/layout.c++:2741: failed: expected builder.isCanonical()
```
in  here: https://github.com/sandstorm-io/capnproto/blob/562f7eabae341172c8706a9eb8bda82b344d4235/c%2B%2B/src/capnp/layout.c%2B%2B#L2741

given
```capnp
struct Ints @0xf8a4d46ee9dd28d7 {
  elt @0: Int32;
} 
```

Works if elt is non-zero.

Was running it at head, 9046dc1ae79514a42b4e59c9cdf6f6372833b9a0

**Comment by dwrensha** [comment]
Thanks for the report! I've submitted a fix: #395.
