### ISSUE TITLE
*.capnp files not installed on Windows

### ISSUE THREAD

**Issue by df2218380513f49d8a3d896fc45740e9** [sandstorm-io/capnproto#398]
this should be easy to fix but I don't know any cmake :disappointed:

**Comment by kentonv** [comment]
It looks like they should be installed along-side the headers. See e.g.:

https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/CMakeLists.txt#L67
https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/CMakeLists.txt#L100
https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/CMakeLists.txt#L121

What are you observing in practice?

**Comment by df2218380513f49d8a3d896fc45740e9** [comment]
I see the headers installed, but not the schemas. The only other thing of note is that I'm using CMAKE_INSTALL_PREFIX to install into a custom location, but given the code you've just pointed me to and the fact that the headers make it, please close this issue if you can't reproduce it!

**Comment by kentonv** [comment]
I haven't actually tried it myself -- I'm not very familiar with cmake.

@pqu @joshuawarner32 any ideas?

**Comment by pqu** [comment]
I unfortunately don't have a Windows machine handy anymore, but the schema files make it into place on a Mac OS X build and I can't see anything obvious that would make a Windows build behave differently.

**Comment by harrishancock** [comment]
Will test this tonight.

**Comment by harrishancock** [comment]
Tried with a custom CMAKE_INSTALL_PREFIX. I cannot reproduce the problem -- for every .capnp.h I see a corresponding .capnp file sitting right next to it.

@df2218380513f49d8a3d896fc45740e9 If you can still reproduce the issue, can you give us the exact sequence of steps that you're taking?

**Comment by kentonv** [comment]
Closing since we can't reproduce.
