### ISSUE TITLE
Builder constructor with nullptr parameter fails to compile

### ISSUE THREAD

**Issue by jcroix** [sandstorm-io/capnproto#402]
The class Builder (line 234 of list.h) has a constructor that accepts nullptr as a parameter and, in that case, doesn't explicitly initialize the member variable "builder", which is of type ListBuilder. Thus the Builder constructor relies on the default constructor of ListBuilder to initialize the variable "builder". The problem is that the default constructor of ListBuilder is no longer present (see layout.h). As a result, code that worked in 0.5.3 doesn't compile in the latest version.

**Comment by dwrensha** [comment]
Interesting! It looks like [this is the commit](https://github.com/sandstorm-io/capnproto/commit/949f7353aaab2a8cc923f3e2451370d9f3c57e24) where `ListBuilder`'s constructor changed.

**Comment by kentonv** [comment]
Heh, the type system did its job -- I removed the default ListBuilder constructor because it lacked the information it needed to behave correctly. But I guess none of the tests were exercising the null constructors. Fixed.
