### ISSUE TITLE
where can I find a tutorial about how to load schema from a file

### ISSUE THREAD

**Issue by nneesshh** [sandstorm-io/capnproto#409]
just like the title.
With protobuf, i write code like "
        _sourceTree = new google::protobuf::compiler::DiskSourceTree();
	_sourceTree->MapPath("", "./dynamic_pb"); //look up .proto file in target directory

	_importer = new google::protobuf::compiler::Importer(_sourceTree, nullptr);
	_dmFactory = new google::protobuf::DynamicMessageFactory();
..."
after load proto from file, I can lookup descriptor from the pool.

I want to do the same thing with capnp.
Any help is much appreciated.

**Comment by nneesshh** [comment]
Is schema_parser the right solution?

**Comment by kentonv** [comment]
Hi @nneesshh,

Yes, `capnp::SchemaParser` is what you want. You will need to link against `libcapnpc.so` in addition to `libcapnp.so` to use it. Documentation is in the header file:

https://github.com/sandstorm-io/capnproto/blob/master/c++/src/capnp/schema-parser.h

**Comment by kentonv** [comment]
There isn't a tutorial, but here's some code from Sandstorm which uses SchemaParser to read a constant file defined in a capnp file:

https://github.com/sandstorm-io/sandstorm/blob/master/src/sandstorm/spk.c++#L293
