### ISSUE TITLE
why underscore is reserved by capnp proto?

### ISSUE THREAD

**Issue by nneesshh** [sandstorm-io/capnproto#412]
Hi, you nice guys. 
Capnp is an amazing work for us. 

But
"Cap'n Proto declaration names should use camelCase and must not contain "
            "underscores. (Code generators may convert names to the appropriate style for the "
            "target language.)"

It seems not a good idea.
I want to map database table fields with capap proto, all the database table field is lower case words with underscore as delimiter.

I can't change the database table, now how can i do the mapping?
Any ideas?
My database middle ware still has any hope?

**Comment by katreniak** [comment]
E.g. enum options are camelCase in .capn and are translated to CAPITAL_WITH_UNDERSCORES for c++ enum options. 

You shall be able to do something analogous in your code, if your table fields are consistent. You can also attach annotations in .capnp file to store database field names explicitly.

**Comment by nneesshh** [comment]
thanks, katreniak.
can you explainshow me how can I use underscore with annotations?
suppose I got a table like this:

message ConfigRoleLevel {
	required int32 level = 1;
	required int32 exp = 2;
	
	required int32 shipyard_capacity_add = 11;
	required int32 cardbox_capacity_add = 12;
	required int32 equipstore_capacity_add = 13;
}
(It is just the protobuf message I used to mapping a table)
how to attach annotation to it in capnp proto file?
does the annotation can be parsed through capnp schema?

Another question:
If the annotation is not the reasonable way, how about changing capnp source code to allowed underscore? Does it mean a lot of work?

**Comment by kentonv** [comment]
You can transform names algorithmically. For example, "shipyardCapacityAdd" -> "shipyard_capacity_add". Assume that each capital letter is the beginning of a word, and transform it into a lower-case letter with an underscore before it.

Otherwise, you can define an annotation:

    annotation dbName(field) :Text;

    struct ConfigRoleLevel {
      ...
      shipyardCapacityAdd @11 :Int32 $dbName("shipyard_capacity_add");
      ...
    }
