### ISSUE TITLE
Question: Can "AsyncIoContext" create by setupAsyncIo support a "RunOnce" method?

### ISSUE THREAD

**Issue by nneesshh** [sandstorm-io/capnproto#434]
I can't get loop handle from "AsyncIoContext"， so I can't update the loop with loop.run() method in my own loop. It seems that the only way to use "AsyncIoContext" is through "wait(WaipScope)".
Does this design has special purpose?
Can I use "setupAsyncIo" interface to implements a message comunicate only network, not RPC?
I am not good at network design, any help is apprciate.

**Comment by kentonv** [comment]
Hi @nneesshh,

Normally the only time you'd call `run()` directly is when you are trying to integrate KJ's event loop with some other event loop system, e.g. libuv, boost asio, libevent, etc. If you are doing that, you can't use `setupAsyncIo()` -- you need to use the lower-level APIs directly to create your event loop and implement the various interfaces correctly for your event API. You can see an example where I did this for libuv in the top part of this file: https://github.com/kentonv/node-capnp/blob/node4/src/node-capnp/capnp.cc

But if you aren't using an external event loop, then you probably don't want to call `run()`.

The KJ async library offers an async networking interface via `AsyncIoProvider` (which you can find in your `AsyncIoContext`). If you want to use the network directly (not through Cap'n Proto), that's the best way.

Note that if you're writing a server and you want to tell the event loop to "run forever", you can do:

    kj::NEVER_DONE.wait(io.waitScope);

If you want it to run until you tell it to stop, you could use a PromiseAndFulfiller for this:

    auto paf = kj::newPromiseAndFulfiller<void>();

    // Arrange so that paf.fulfiller->fulfill() will be called when you want to exit...
    setMyExitHandler([&]() { paf.fulfiller->fulfill(); });

    // Run until the exit handler is called.
    paf.promise.wait(io.waitScope);

**Comment by nneesshh** [comment]
Hi, @kentonv, thank you for your prompt explanation.
Now I am trying to use kj loop as my main loop, and I want schedule my OnUpdate() function through evalLater() or timer.afterDelay(). My code like this:

       auto ioContext = setupAsyncIo();
	kj::evalLater([]() {
                // do update here, it will call kj::evalLater again, so I can't use wait on evalLater promise.
		printf("eval later once!!!");
		return kj::READY_NOW; // return a promise to disable optimize
	}).eagerlyEvaluate(nullptr); // eagerlyEvaluate to disable optimize
	bool _scheduled = true;
	kj::NEVER_DONE.wait(ioContext.waitScope);

But the evalLater callback was never called.
I am using vs2015 update3, and I only can tell that the loop->head var was empty when kj::NEVER_DONE.wait.
The eagerlyEvaluate func was once valid, but the loop head was cleard after that for some reason I can't explain.
 Is my code wrong? Or must I wait the evalLater promise?

**Comment by katreniak** [comment]
I guess that the you need keep promise from `kj::evalLater` alive. E.g. by storing it to local variable or to `kj::TaskSet` instance. I recommend `kj:TaskSet`.

I believe that kj tutorial shall much better promote class `kj::TaskSet`. It was the biggest missing piece of kj puzzle for me after I read the (great!) tutorial.

**Comment by nneesshh** [comment]
Hi, @katreniak , thanks for your help.
You are right, after add a varibale to store the promise,  the code works fine.
I guess the promise var is the only event handle in kj, so if it was released, the promise is cancelled at once.
It is a good design, and it is just a little difference with other event loop.
