### ISSUE TITLE
c++/src/kj/compat/http.c++: PVS-Studio: The 'memcmp' function processes '0' elements.

### ISSUE THREAD

**Issue by SvyatoslavRazmyslov** [sandstorm-io/capnproto#445]
We have found a bug using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

We suggests having a look at the emails, sent from @pvs-studio.com. 

Analyzer warning: V575 The 'memcmp' function processes '0' elements. Inspect the third argument. http.c++ 90

**http.c++:**
```
static kj::Maybe<HttpMethod> consumeHttpMethod(char*& ptr) {
  char* p = ptr;
  ....
  case 'U':
    switch (*p++) {
      case 'R': EXPECT_REST(PUR,GE)
      case 'T': EXPECT_REST(PUT,)   // <=
      default: return nullptr;
    }
  ....
}
```
**http.i:**
```
case 'U':
  switch (*p++) {
    case 'R': if (memcmp(p, "GE", sizeof("GE")-1) == 0) { .... }
    case 'T': if (memcmp(p, "", sizeof("")-1) == 0) { .... }
    default: return nullptr;
  }
```

**Comment by kentonv** [comment]
Thanks for the report.

This is not a bug. It's common for macros to expand to redundant code in degenerate cases. Designing the macro to avoid this is hard, and wouldn't help: the compiler is already smart enough to elide the call.

**Comment by dwrensha** [comment]
I was confused when I read this code, but then I remembered the counterintuitive fact that in C/C++ `sizeof("")` is equal to `1`, not `0`, due to null-termination.
