### ISSUE TITLE
ENOPROTOOPT trying to set SO_RCVBUF on Hurd

### ISSUE THREAD

**Issue by thomaslee** [sandstorm-io/capnproto#456]
It's always hurd. :)

@kentonv I think we've spoken about this before, but I wanted to get it "on-record" since I don't recall the details of our conversation:

hurd-i386 tests are failing on Debian build boxes due to an ENOPROTOOPT trying to set SO_RCVBUF:

https://buildd.debian.org/status/fetch.php?pkg=capnproto&arch=hurd-i386&ver=0.5.3-2&stamp=1474272541&raw=0

Per http://polarhome.com/service/man/?qf=unix&tf=2&of=Hurd&sf=7

> The SO_SNDBUF socket option does have an effect for UNIX	 domain	 sockets,  but  the  SO_RCVBUF  option  does not. 

So I'm making a bit of a leap and assuming that the ENOPROTOOPT errno is Hurd trying to tell us that.

I can work around this on the Debian side to feel out whether it's as simple as watching for ENOPROTOOPT and ignoring it if so, but the comment seems to imply that it might be somewhat important for the tests that follow. Can you speak to that at all? I'd much rather keep the tests with some risk that things might slip through the cracks rather than #ifdef the tests away entirely on Hurd.

**Comment by thomaslee** [comment]
Oh and somewhat unrelated, but you might be interested: hurd-i386 is the one last architecture that doesn't currently have a working capnproto build -- it's green pretty much everywhere else:

https://buildd.debian.org/status/package.php?p=capnproto&suite=unstable

Good stuff :+1:

**Comment by kentonv** [comment]
Hmm, it sounds like because unix sockets are entirely local, they only have one buffer, not two, and so you're only supposed to set a size on the send buffer. Makes sense. The code already sets a size on the send buffer, so if I'm correct then setting a size on the receive buffer is not necessary.

That said, to be safe, let's keep both calls, but take the KJ_SOCKCALL wrapper off the recvbuf one so that the error is ignored...

**Comment by thomaslee** [comment]
Yep, have a patch on the Debian side more or less to that effect: if setsockopt fails and `errno != ENOPROTOOPT`, fail the test -- otherwise continue as normal. Not exactly elegant, but at this stage just trying to verify it gets us a little further.

**Comment by kentonv** [comment]
So with that change, does the hurd build succeed?

**Comment by thomaslee** [comment]
Too early to say -- Debian's in a freeze, so the only thing I'm likely to get past the release team is the security fix from last week. Once the release goes out I'll give Hurd another shot with my change.
