### ISSUE TITLE
VS2017 ICEs at kj/common.h:824

### ISSUE THREAD

**Issue by harrishancock** [sandstorm-io/capnproto#466]
[Continuing the discussion from #464.]

While the ICE appears to originate from inside `kj::dtor()`, it seems like an exacerbation of whatever bug required the workaround in commit 19096841c85c. Briefly, we have:

```c++
template <class T>
class NullableValue {
public:
  // ...
  inline ~NullableValue() noexcept(__is_nothrow_destructible(T)) { ... }
};
```

If I change the `noexcept` specifier to `noexcept(false)`, or if I omit it entirely, VS2017 compiles everything and all tests pass.

**Comment by kentonv** [comment]
I would be OK with making it `noexcept(false)` for MSVC. I think the only ill effect should be that STL containers will tend to prefer copy-construction rather than move-construction in cases where both are available. KJ containers aren't so pedantic.

**Comment by harrishancock** [comment]
I'll submit a PR.
