### ISSUE TITLE
Rename MD5 code so that people don't think it's a security issue

### ISSUE THREAD

**Issue by DemiMarie** [sandstorm-io/capnproto#482]
Finding collisions in MD5 is trivial, and even HMAC-MD5 is not recommended (though still not broken in practice).

**Comment by kentonv** [comment]
Cap'n Proto's use of MD5 is not security-sensitive. We use it to generate 64-bit type ID numbers if the developer didn't specify one explicitly. The developer is free to specify whatever type ID they want, hence if they want to collide, they can trivially do so -- this is expected. MD5 is only used to avoid accidental collisions.

I do wish I had chosen some other algorithm so as not to freak people out, but changing this now would break backwards-compatibility.

**Comment by kentonv** [comment]
Maybe we should rename the code to remove "MD5" from the name and instead call it "non-cryptographic deterministic random number generator for type IDs".

**Comment by DemiMarie** [comment]
Okay, makes sense.
